// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= DTDs for annotations to KML files

== Status

Proposed

== Context

We have a story to produce a https://jira.tomtomgroup.com/browse/NAV-18163[maneuver coverage report].  We will build this out of several tools that use KML files as intermediate file formats.  The KML files will be annotated with custom XML data.  We need a solution for:

* Validating KML files with annotations
* Tracking changes in annotation format over time
* Checking backwards compatibility of tools

== Decision

We will not make any immediate effort to define DTDs for the immediate work.  It is lower priority than delivering the needed outcome, of tracking improvements in maneuver coverage in the instruction engine.

== Consequences

* For initial variants of the annotations we will be using "anonymous" structures whose version is not tracked.
* We will be defining XML namespaces that do not refer to any real structure
