// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Definition of Roundabout Exit Angles

== Status

Implemented

== Context

We have a story to https://jira.tomtomgroup.com/browse/NAV-16736[Correct Angles for Roundabouts with V-shaped exits].  We have several ideas for how to adjust these angles:

* Currently we use the ratio between the distance from entry to exit and the circumference, expressed as an angle
* We could use the difference between the incident angles of the entry and exit where they join the roundabout
* Instead of the above angles calculated for the exit itself, we could average between the exit and its corresponding entry
* We could use the angle at the point where the road in both directions "becomes straight"

We can't be sure which angles will be most effective, now or in the future.

== Decision

We will capture multiple different angles in the Exit structure of the roundabout model.  Initially, we will have two:

* `distance_ratio_angle`: Ratio between the distance from entry to exit and the circumference, expressed as an angle
* `incident_angle_diff`: Angle of the exit road at the point it meets the roundabout, relative to the equivalent angle of the entry road

== Consequences

* We can flexibly choose or even combine these angles to produce the most intuitive description of the exit for the driver
* We can dump all angles in the log, which will make it easier to interpret the decisions of the roundabout model builder
* Every type of angle must be computed during model building, regardless of whether it is actually required
