// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Location of Python scripts

== Status

Proposed

== Context

We have a story to produce a https://jira.tomtomgroup.com/browse/NAV-18163[maneuver coverage report].  We would like to use Python as far as possible ([[2020-06-29T13:35:13-scripting-language]]).

Other Python tools such as the copyright-checker have dedicated repositories.

== Decision

We will add the Python code into the existing nk2-navigation-instruction-engine repository, and build it with our existing Jenkins pipeline.

== Consequences

* The version of the Python tools will be the same as the instruction engine C++ library
* Python unit tests should be fast and robust, to avoid blocking the main C++ CI
