// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Roundabout Angle Calculation

== Status

Implemented

== Context

We have a story to
https://jira.tomtomgroup.com/browse/NAV-16734[Improve Angles for
Roundabouts with tangential incident roads].  We need to implement an
improved algorithm for estimating the perceived angle of these exits.

We previously [[2020-07-30T13:52:47+0200-roundabout-angle]] decided to
estimate the angle of an exit as the angle between the center and a
"distant point" 50m along the road.

However, this approach failed for some large roundabouts. This is
mostly because the point 50m along the road was sometimes still on the
"V" of the "V-shaped exit".  Furthermore, on large roundabouts the
road often does not head towards the center of the roundabout.

We moved the distance point on both sides of the roundabout,
i.e. entery and exit. There was improvement in angles but still fail
to get the right direction. Also tested with 100m the results didn't
improve for very large roundabout.

In addition, the previous algorithm was hard to explain:

* Why does it adjust the exit position but not the entrance position?
* Where did "50m" come from?
* How exactly is the center point calculated?
* The search for a distant point stops at the first bifurcation, which
  is fragile and hard to explain

== Decision

* We will calculate the turn angle of the roundabout as the difference
  between the angles of two arcs that are one roundabout-diameter away
  from the entrance and exit
* To find these arcs, we follow the previously-defined "natural
  continuation" of the road - even if this is not the actual path
  taken by the route
* The angle between the arcs will be based on the angles reported at
  the ends of the arcs - not by calculating the angle between the
  start and end of the arc
* There are still some edge cases where the V-entry and V-exit is
  longer than the diameter of the round about. While taking U-turn on
  such roundabout, the angle of the arcs was over-estimated enough to
  produce wrong direction. We can detect those cases and we have
  implemented a check to remove this issue.

== Consequences

* The behaviour of the roundabout algorithm now has to be explained in
  terms of "natural continuation", which is rather empirical
* The angle we use to describe the roundabout does not necessarily
  correspond to the angle the driver actually drives along
* Because we follow the natural continuation, we do not need to
  implement backwards iteration along the route
* If the arc found is twisty, it is hard to explain how the angle was
  calculated
