// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Mock maps attributes

== Status

Proposed

== Context

When writing a mock map for testing purposes two approaches can be followed
* 1.Create a mock map with only the necessary attributes.
* 2.Replicate the map with a lot of attributes that the instruction engine might use in the future.

With the approach 1 we have very small mock maps which are easy to read. While implementing more features we might need to modify them
to include more attributes.

With the approach 2 we can easier reuse the mock maps from different tests because they describe a real map situation. Also, we can port
mock maps from NK1 to NK2. On the other hand, we can't be sure that all the map attributes are correct because there is no way to verify them.
Also the mock maps might become too large and more difficult to read.

== Decision

We feel there is no strong need for alignment here. Different styles of GXL files are acceptable, particularly for those imported from other sources such as NK1.

== Consequences

* No review comments to add/remove attributes in mock map
* Easy porting of NK1 mock maps
* Inconsistency in the approach of writing a mock map
