// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Strategy for Mock Builders

== Status

Proposed

== Context

We currently have two implementations of mock junction model builders:

* LineAttributes is a struct designed for recording expectations, which can be used to build a MockLine with expectations set
* MockJunctionModel is a builder class that creates a network of junctions and lines, with some attributes set

The two currently cannot be used together.

== Decision

MockJunctionModel's AddLine function will be extended with an optional LineAttributes argument.

== Consequences

* As LineAttributes is extended with more attributes, they will be available to MockJunctionModel automatically
* LineAttributes objects can be reused multiple times for similar lines
* We will see nested "fluent API" style call chains in unit tests
