// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Replacing StrictMock with NiceMock

== Status

Proposed

== Context

With this commit I changed all of the mock objects used in unit tests to StrictMock:

....
commit 1bbf96650dc0eb076c3ab3e10de7a5a7acc14546
Author: Matthew Exon <Matthew.Exon@tomtom.com>
Date:   Thu Jun 18 11:08:11 2020 +0000
....

However this is https://chromium.googlesource.com/external/github.com/google/googletest/+/HEAD/googlemock/docs/cook_book.md[not recommended]:

____
Our general recommendation is to use nice mocks (not yet the default) most of the time, use naggy mocks (the current default) when developing or debugging tests, and use strict mocks only as the last resort.
____


== Decision

We will use NiceMock for new code unless there is a good reason for using StrictMock.
Though, it must be observed that NickMocks have an undesired behavior: they suppress a warning when an unexpected call is issued and return a default value. That is troublesome when tests break after a change in implementation: one does not know what method of the call is now silently returning an unexpected default value.
That being said, we will encourage developers to use NiceMocks, but there will be no wholesale replacement of StrickMocks.



== Consequences

* It may be harder when writing unit tests to understand exactly which function calls are being mocked and which called for real
* Unit tests should be more robust to changes in implementation
* We will be making greater use of the default return value functionality in gmock
