// Copyright (C) 2020 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= TurnHandler (Simple intersection handler)

== Overview
The `TurnHandler` class is responsible for simple Instruction generation: turn (slight/sharp)
left or right (`Instruction::Type::kTurn`) and legally obligatory turn
(`Instruction::Type::kObligatoryTurn`) +
*UX spec:* https://confluence.tomtomgroup.com/display/FlaminGO/NIE_011+-+Turns+instructions#NIE_011Turnsinstructions-%22Turn%22Instructions[Turn instruction] +
*Legally forced turn:* https://www.google.de/maps/@52.5312622,13.4808577,3a,75y,83.73h,92.07t/data=!3m7!1e1!3m5!1sG8FyMA-TDRcuf3M1bbwsnA!2e0!6s%2F%2Fgeo0.ggpht.com%2Fcbk%3Fpanoid%3DG8FyMA-TDRcuf3M1bbwsnA%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D71.50113%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656[example]


== Rules of instruction generation
If the route is going to 'natural continuation across a junction', then the intersection IS
consumed by the handler, but the instruction is suppressed. Otherwise, a turn instruction
is issued.

If the outgoing line on route is the only option, then instruction is obligatory
(`Instruction::Type::kObligatoryTurn`).

== How to detect natural continuation
Please refer to the documentation about "natural road continuation".
*Implementation:* _RoadContinuationDetector class_
*Method:* _IsContinuingAcrossJunction member function_

== What Turn to street name is taken
The street name for instruction (turn to street name) is taken from the first line on the route,
after the intersection, that has `is_plural_junction` attribute with value `false`.

== How directions are calculated
The instruction Direction is calculated as relative angle from the line before intersection and
the first line on the route, after the intersection, that has `is_plural_junction` attribute
with value `false`.
[%hardbreaks]
The angle's range is from `-180 to 180`.
`kStraight - (-10;10)`
`kSlightRight - [10;60)`
`kRight - [60,120)`
`kSharpRight - [120,180]`
same for left in the opposite direction.

*Implementation:* _ConvertAngleToDirection function_
