// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Incremental instruction computation

== Status

Accepted

== Problem
Currently the lane guidance provider has a map access container which holds a lock to the map during the lifetime of the provider.
This prevents any map update from happening. The initial solution was to delete the
lane guidance provider for every call to the OnDataChanged in the OTGM and also deleting the lane guidance tracked scenario.
This is causing issues in the case of combined maneuvers because clear the state at the middle of a junction and provide
a completely new scenario.

== Solution

Pass the map access provider to the lane guidance provider and create a map
access container only when calculating the lane guidance scenario. This way we won't have any problems due to the map update.
It will also allow us to keep the lane guidance provider alive in cases we receive a call to OnDataChanged in the onboard
trip guidance manager.
