// Copyright (C) 2021 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Handling Lane Group Feature References

== Status

Accepted

== Context

The `LaneGuidanceBuilder` reads lane groups attached to each arc of
the route, along with selected off-route arcs, and uses them to build
a lane guidance scenario.  Currently this scenario has gaps in the
on-route path, because some essential lane groups are shared between
multiple arcs.

In the case of shared lane groups, the FTX block encodes the full lane
group data as a `FTX_LANE_GROUP` property of one arc, while other arcs
only include a `FTX_LANE_GROUP_FEATURE_REFERENCE` property which
points to the lane group number and original arc.

We have a user story
https://jira.tomtomgroup.com/browse/NAV-51387[NAV-51387] to use these
lane group feature references to fill the current gaps in lane
guidance.

== Alternatives

All implementation options are relatively small changes to the
existing architecture.  Currently the `LaneGuidanceProvider` passes a
route stretch of arcs to the `LaneGuidanceBuilder`, which first
iterates over the on-route arcs to accumulate lane groups, then
iterates over the off-route arcs to accumulate more lane groups.

=== One Pass With Index

In this option we continue iterating over each of the arcs one at a
time.  We will also need to keep a record of lane groups that have
already been seen.  We can then add all the lane groups that are
direct properties of the arc, as well as chase up references and add
those lane groups too.  However we need to keep an index of lane
groups that have already been seen, in order to avoid adding the same
lane group twice.

=== Second pass to fill in gaps

In this option the existing loops are kept as is, and a second pass is
added.  In this pass we chase up lane group references and add the new
lane groups.

=== Second pass looking for connectivity gaps

In this option rather than iterating over the arcs in a second pass,
we iterate over the connectivity map looking for lane groups that are
not properly connected.  We can then efficiently look at the lane
group references only of the arcs corresponding to these gaps.

=== Decision

From these alternatives, we decided to do a single pass that looks up
lane group references of all the arcs.

== Handling of shared lane groups

When the `LaneGuidanceBuilder` finds a lane group that has already
been added, there are two ways to handle that situation:

=== Merge in separate pass

In this alternative, the lane group is added twice to the scenario,
once as a direct link property and once as a reference.  Then a second
pass is necessary to collapse repeated lane groups.  These repeats can
be detected because they have the same source and destination
connector IDs.

This approach works well when the shared lane group is in the middle
of two parallel arcs.

The advantage of this approach is it takes us closer to an ideal
presentation of the lane guidance scenario.  In the future, in
general, these cases represent splits in the road, in which parts of
the lane group belong to one fork and the remainder to another fork.
We could improve lane guidance by splitting the lane group by lane in
this second pass, keeping two lane segments.

However, it is currently not clear if this really is desired
behaviour, or if clients would prefer to see the full range of lanes
in the NIP, even if some of those lanes are unreachable.  It also
appears that some of these cases are groups of lanes separated by a
gore.  In the case the car can physically drive across the gore if
necessary.  It may be desirable for the "unreachable" lanes to be
indicated, if only to actively discourage the driver from trying to
reach them.

=== Do not add new segments, but extend by validity range

In this alternative new segments are not added if the referenced lane
group is already represented by a lane segment.  However if the
validity range of the reference is beyond that of the existing
segment, and the lane group is on-route, that segment's range is
extended.  If the lane group is a property of an off-route arc, or is
reference by an off-route arc, that off-route part should have no
effect on the segment's range and that part is discarded.

This approach is most clearly appropriate where the shared lane group
is at an arc boundary.  In the case that the shared lane group is in
the middle of two parallel arcs, we would set the lane group's offsets
according to the on-route arc, and ignore the validity range of the
part on the off-road arc.

This is more targeted towards the case that a lane group overlaps two
consecutive arcs.  In this case we would prefer to keep one lane
group.

In the case where the lane group is shared between two parallel arcs,
there can be a situation where the lane group is marked as off-route,
which leads to a discontinuity in the off-route lane groups.  The
intermediate section would still be present in the scenario, but it
may be counterintuitive that consecutive lane groups may be in the
sequence off-route, on-route, off-route.

=== Decision

We will not add new segments when they are already represented, and we
will extend the validity range of existing segments.

There wasn't much to choose between the two options, but this approach
seemed a slightly more intuitive design.  We may indeed later want to
split lane segments by lane, but we can fairly easily switch our
approach when the requirements for that are clearer.

== Consequences

* Some non-drivable lanes will be included in on-route segments that
  are really present on off-route arcs
* Splitting lane segments by lane may be a slightly larger change in
  future
* Where a lane group overlaps two parallel arcs, the entire group
  would be marked as on-route, while the off-route polyline would have
  a gap
