// Copyright (C) 2021 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Lane guidance builder Challenges
:Date:      2021-08-20
:Revision:  0.1

Lane guidance builder generates the lane Scenario from given set of on route and offroute arc keys.

Lane Scenario is a Set of laneSegments i.e. lane segments which are part of the lane guidance scene.
[source,cpp]
----
Lane segments contain information three types of information
{
    Lanes
    Center-Polyline

// Some Segment related properties
   start_offset_on_route{};
   end_offset_on_route{};

  DrivingSide {left, right}
  segment_id
  bool is_maneuver
  bool is_on_route

// Some data access related fields
  lane_group_id
  arc_key;
}

//Similarly we have Lane
{
    Divider_driving_side
    Divider_non_driving_side
    LaneType
    Connections_to_other_lanes

    Arrows(can be recommended and not-recommended)
}
Detail of this is out scope for this document.
----
With time this module (Lane Guidance builder) has grown in complexity. We would like to simplify and address the challenges listed below.

== Challenges
== Referenced Lane Groups
=== Lane Group appears Only Once(in our scenario), but has references.
For this lane group we have complete connectivity, complete poly-line and complete set of dividers but this doesn't apply to whole length of the lane group. So the whole poly-line and dividers don't apply to corresponding validity range. We can clip the poly-line or dividers for this but there is no clear way where to trim them(from end or start or middle).
These lane groups create bigger problem when they happen to be on first arc and last arc.(Trimming away the first part for the first arc and last part for last_arc is not completely right solution.)

=== Lane Group Appears Multiple Times(in our scenario) On-route
Right now when a lane group appears multiple we are just extending its validity range. (all other properties of lane group are complete in all copies of lane group). So as the lane group is complete it can have excess data(poly-line and dividers). This might refer to references which are not in our scenario.

=== Lane Group Appears Multiple Times(in our scenario) On-route, Off-route
When the lane group appears in off-route arcs we discard it, if this was already found on any of on-route arcs. This means we may or may not have some extra information about dividers and poly-lines in our generated on route segments.

=== Lane Group Appears Multiple Times(in our scenario) Off-route
We discard the second copy. Off-route segments don't have offsets. We might have some extra data(poly-line and dividers) but as it is off-route and extra data would also be off route. It might not affect our output(extra data is also valid, there are no promises about how much data we would provide). This is mentioned for completeness.


== Parallel Lane-groups
Sometime two(or more) lane groups are parallel to each other. According to standard they should not share any lanes(to my understanding). Some part of our pipeline are constructed in such a way we need to have in sequence.
This creates the problem of having wrong offsets.
We would like to decide what needs to be done for these lane-groups. We need to decide how they should be handled.

* Have both(or more) and keep them at same offset.
* keep only one of them.
* merge them to make on lane-segment(if both had two lanes each the result would have 4).



== Different Dividers and lane types at some part of the(lane) inside lane-group.
Our external API is simple representation of the lane-group-(aka laneSegment(API level, not internal)). In this structure our lanes have same attribute throughout the lane group. For this we have to split the lane segment.

== Arc to lane-group matching
Ftx presents lane-groups which may be matched on several arcs. (example: Ftx split can happen before or after arc split)

=== Ftx split Later than arc split
This happens due the fact the lanes split after the arcs are split. We have already decided we should move segment by segment for arrow synthesis and then to find relevant angles we can go in reverse traversal to find arcs get right angles(We might be also tempted to find angles from poly lines as they might be more accurate(that has not been discussed with anyone yet.))
Three slight right arrow bugs are classic symptom of this problem (they are not only symptoms).

=== Ftx Split before arc split
The above solution should work in this case as well, but now we have to do forward traversal to find arc.(and may be this pins down to my idea of using poly line.). There might be other solutions possible for this situation.
No arrows bug is classic example of this, but problem is not limited to this case only.
