// Copyright (C) 2021 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Handling HOV entry and -exit situations

== Status

Proposal.

Instruction generation has been implemented by NAV-52423 and NAV-52424.
Lane guidance for HOV instruction is not yet implemented.

The instructions do not yet take into consideration these restrictions before deciding whether to take the HOV lane:
- lane can be driven at the position ETA;
- lane can be driven given number of passengers in the vehicle;
- lane can be driven given car engine (electric vs combustion).

This information should soon be made available by the routing engine.

== Glossary

*HOV entry* is the position where we place the _EnterHov_ instruction.

*HOV exit* is the position where we place the _ExitHov_ instruction.

*Road exit* is the position where an exit/switch/fork/turn instructions is generated, which takes you away from the road where the driver was driving in the HOV lane. The existence of a road exit has the implication that, if the driver is using the HOV lane, they will eventually need to leave it in order to stay on route. An _ExitHov_ is likely to be produced in this case.

== Rules for generation of _EnterHov_

This is mostly based on the requirements from Audi:

- The driver must be driving in the motorway for at least *1 mile* before we can issue the _EnterHov_;
- The HOV entry requires a lane divider that allows crossing from non-HOV to HOV;
- The HOV entry may take place in the middle of a _LaneDataSegment_ (if that is required to comply with the above mentioned minimum distance in the motorway);
- It is only worth generating _EnterHov_ if the driver can stay in the HOV lane for at least *2 miles* (starting from the HOV entry).

== Rules for generation of _ExitHov_

This is mostly based on the requirements from Audi:

- The HOV exit requires a lane divider that allows crossing from HOV to non-HOV;
- The HOV exit requires a minimum distance of *2 miles* to the road exit;
- The HOV exit takes place in the beginning of its _LaneDataSegment_ (so the driver is guaranteed to have time for leaving the HOV lane).

And with special importance:

- We suppress the generation of _ExitHov_ if, between the HOV exit and the road exit, the driver is never forbidden to leave the HOV lane.

Our interpretation of this rule (suggested by Audi) is the following:

The _ExitHov_ serves the purpose of warning the driver to leave the HOV while they can, because the HOV lane can later become closed again, in which case they may not be able to take the road exit in time. Thus, when there is nothing preventing them to leave the HOV until the road exit, there is also no reason to warn them, and an instruction is no longer justifiable. We can derive from this understanding two others rules:

- *Rule X1*: If the HOV lane comes to an end at least *2 miles* before the road exit, _ExitHov_ must be suppressed;
- *Rule X2*: If there is no road exit, _ExitHov_ must be suppressed.

== Detection of HOV entry

The situation handler delegates the work of detecting a situation for _EnterHov_ to the _EnterHovSituationDetector_.

The detector only advises for issuing _EnterHov_ under these conditions:

- All rules for _EnterHov_ are satisfied;
- Given the HOV entry and past 2 miles of contiguous HOV lane, find the next possibility of exiting the HOV lane and call it "HOV exit candidate". If the distance between the HOV exit candidate and the road exit is less than 2 miles, do *not* generate _EnterHov_. (Rationale: this is the verification of a boundary condition. It does not actually matter where _ExitHov_ will actually be issued.)

Such an approach guarantees that, once we advise for issuing _EnterHov_, it can for sure be generated. No matter what comes later on the route, we will never need to take back the _EnterHov_. In this sense, detecting HOV entry is completely independent of the detector for HOV exit.

Moreover, we distinguish three situations where the _EnterHov_ might come up:

* HOV departure - Route departs already on motorway and, past 1 mile still on it, a HOV lane is already available (implemented by _EnterHovSituationDetector::IsRouteStartingOnMotorwayThenTakingHov_);
* Entering motorway with HOV - Steps into motorway and, past 1 mile on it, a HOV lane is already available (implemented by _EnterHovSituationDetector::IsEnteringMotorwayThenTakingHov_);
* HOV starts in the motorway - While driving in the motorway, the HOV lane starts in front of the driver (implemented by _EnterHovSituationDetector::IsOnMotorwayThenTakingHov_).

.Guarantee
***
*G1*: Whichever situation is tested by _EnterHovSituationDetectorInterface_, the implementation guarantees that at least the first line has been fully scanned. If no HOV entry could be found, one can be sure that no _EnterHov_ is to be issued for the first line in the range.
***

The detection returns the exact offset on route where the _EnterHov_ needs to take place. When no position is returned, *G1* implies that *no* _EnterHov_ instruction is to be generated for the first line provided. However, a subsequent call may detect an HOV entry in the next line on route.

== Detection of HOV exit

The situation handler delegates the work of detecting a situation for _ExitHov_ to the _ExitHovSituationDetector_.

The detector only advises for issuing _ExitHov_ when all rules for it are satisfied. This is implemented by _ExitHovSituationDetector::IsExitingHov_, that scans an interval of the route, which may start at any position within a line. The detection returns the exact offset on route where the _ExitHov_ needs to take place, plus the last line that it analysed. Also when no HOV exit is detected, the last line analysed should *not* be provided again in a subsequent call, so this line can be considered "consumed".

.Guarantee
***
*G2*: The occurrence of _ExitHov_ *always* implies the existence of a later maneuver taking the driver out of the road. (See rules *X1* and *X2*.) This is the road exit and it *must* take place at the head of a line. Between the _ExitHov_ and road exit no other HOV instruction can possibly exist. As a consequence, the issuance of a HOV exit allows us to safely consume the lines up until the road exit. If no HOV exit is found, we consume only the first line of the given range.
***

.Constraint
***
*SC2*: The current implementation expects the first lane segment of the given interval to have a recommended HOV lane, otherwise it quits immediately. In this case, the first line of the given range will still be consumed (so we can comply with *G2*).
***
IMPORTANT: Under very particular circumstances, this behavior will cause an _ExitHov_ instruction to be missed for this first line. This is however a very rare corner case, and we decided not to handle it, for the sake of keeping the code as simple as possible.

== Behavior of LLR and its importance

The situation detection and handling uses lane data that is exclusively provided via the _LaneDataFetcherInterface_.
The _LaneDataFetcherImpl_ relies on the _LaneGuidanceBuilder_, which on its turn makes use of the _LaneLevelRouter_ (LLR) in order to determine which lanes of each segment are recommended.

The _LaneDataFetcherImpl_ has an own instance of _LaneGuidanceBuilder_, which tweaks the LLR algorithm to work differently. When computing the cost for lane level routes, the LLR will then assign a bonus negative score for the HOV lanes, hence favoring a route taking the car pool over all others, as long as such a route is possible. That means: it will only recommend taking the HOV lanes if, within the considered route stretch, it is possible to cross the lane dividers to enter and/or exit the HOV lanes.

What the LLR does not guarantee however, is the adherence to the minimum distances required by the rules for HOV entry & -exit. The lane level routes that take the car pool are expected to stay in the HOV lane up until the very last moment, before taking the driver towards the road exit. For this reason, the _EnterHovSituationDetector_ and _ExitHovSituationDetector_ use the _LaneDataSegment_'s provided by the _LaneDataFetcherInterface_, and rely on the recommended lanes ultimately calculated by the LLR, but in the end, these detectors need to enforce themselves the minimum distances, in order to guarantee that _EnterHov_ and _ExitHov_ are placed correctly.

== The situation handler

The _HovLaneHandler_ is responsible for issuing both _EnterHov_ and _ExitHov_ instructions. This design is a consequence of a few properties of the instructions, constraints of situation handling and detection algorithms:

(A) Like any other situation handler, the _HovLaneHandler_ may only consume lines in its entirety. This is a restriction of the _SituationHandlerInterface_. Because the handler cannot resume from a position in the middle of a line, it should not quit before analysing the whole line, otherwise the not-analysed portion is skipped and any possible instruction there is lost.

(B) The _EnterHov_ may take place at any position within a line. After the _EnterHovSituationDetector_ finds out such a position, between that and the head of the same line, if this line is long enough, an _ExitHov_ may still take place. As a consequence, because of (A), this line cannot yet be consumed. It needs first to be analysed by _ExitHovSituationDetector_.

(C) Given the scenario described in (B), the _ExitHovSituationDetector_ must analyse the line starting from the position of the HOV entry. This is compliant with the constraint *SC2*.

All taken into account, we devised the following process for issuing the _EnterHov_ and _ExitHov_ in the situation handler:

* Try to detect an HOV entry using _EnterHovSituationDetectorInterface_;
* If a HOV entry has been found, issue an _EnterHov_ instruction and use its position as starting point for a call to the _ExitHovSituationDetectorInterface_;
* If a HOV entry could not be found, call the _ExitHovSituationDetectorInterface_ starting at the tail of the first line;
* If a HOV exit has been found, issue an _ExitHov_ instruction and consume as many lines as *G2* allows;
* If a HOV exit could not be found, *G1* and *G2* imply that at least the first line of the range can be consumed.

== Testing strategy

The _InstructionGenerationHelper_ employs a fake implementation of the _LaneDataFetcherInterface_, that allows us to enrich a mock map with lane data during runtime. (For that, one just needs to use  _InstructionGenerationHelper::AddLaneDataTo_.) For these reason, the collaboration tests with mock maps do not actually test the integration with the _LaneGuidanceBuilder_. (Only tests with the real map are capable of integrating all components.)

The regression tests dispose of a couple of routes in California that run a few miles with HOV lanes. As of the first edition of this document, the quality of the map data from the development drops of MapScapes was so low, that no instruction could be generated. Though, any evolution in the map quality for the next drops is expected to make _EnterHov_ and _ExitHov_ instructions visible.
