// Copyright (C) 2021 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= How to implement turn around when possible instruction

== Status

Proposal

== Tracability
NAV-8408 - Turn around when possible instruction support
NAV-30567 - Compute information to support turn around when possible instruction

== Context
Turn around when possible instruction is issued when the driver is in a route stretch where executing an
u-turn maneuver would shorten the route without skipping any significant waypoint.

Such an instruction is necessary because NavKit does not know if it is safe and/or convenient to execute
a u-turn maneuver at the specified route stretch and therefore the route will make u-turn at the first
crossing and not in the middle of the arc.

== Problem
In order to know where to issue the turn around when possible instruction the system needs to know
the parts of the route where such an instruction can be issued.

== Alternatives

=== #1: Routing engine will expose the u-turn flag

In this solution we propose that since the routing engine keeps the list of already visited arcs
and knows about route legs/waypoints it can add an additional flag in the ArcInfo structures describing the route arcs indicating that
a shortcut is possible.

Advantages:

- other systems like VH can easily expose the u-turn when possible flag

Disadvantages:

- planning requires coordination between BROT and Guidance
- instruction engine will need to consume arc infos

==== #2: Instruction engine computes the u-turn stretches and then instructions

Instruction engine contains all the necessary information to compute the u-turn flag. The solution to keep enchanced route information inside
the instruction engine is not new and we already use simillar approach for SideRoadsExitOffsets.

Advantages:
- no need to use ArcInfos in instruction engine
- no dependency on BROT

Disadvantages:
- computed u-turn arc information is only available to the instruction engine

== Solution

Solution #2 is proposed as it is simpler and as of now we do not have any request to expose the u-turn flag in other components.
