// Copyright (C) 2021 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= format of the KML with arc keys

== Status

Accepted

== Context

In context of https://jira.tomtomgroup.com/browse/NAV-29344[split the Instruction Dumper to dump arc keys], We would like to extend the instruction dumper to additionally dump arc keys, so that
We can use these arc keys to generate instruction in new instruction Engine

== Reasons to rely on arc keys
-    It removed the dependency on trip-onboardservice and allows to debug the NIE without working in two components
-    Easier to get it up running in the CI.
-    Speed and independence from route is also a factor

== Why dump the arc keys into KML?
- To reuse the existing code that already works with the KML.

== Proposed KML file format

This is how kml will look like after adding ark keys:

        <Folder id="arc_keys">
            <name>ArcKeysDumper results</name>
            <ExtendedData xmlns:akd="http://tomtom.com/guidance/arc-key-dumper/1.0">
                <akd:RouteParameters>
                    <akd:originNdsCoordinatesDegrees>11.5996,48.1421</akd:originNdsCoordinatesDegrees>
                    <akd:destinationNdsCoordinatesDegrees>11.5962,48.1419</akd:destinationNdsCoordinatesDegrees>
                    <akd:routeLengthCm>48400</akd:routeLengthCm>
                </akd:RouteParameters>
                <akd:ArcsKeys>
                    <akd:ArcKeyWithOffset>
                        <akd:tileId>545554687</akd:tileId>
                        <akd:featureIdAndFlags>176685058</akd:featureIdAndFlags>
                        <akd:tail_offset_on_route>-1900</akd:tail_offset_on_route>
                    </akd:ArcKeyWithOffset>
                    ...
                    <akd:ArcKeyWithOffset>
                        <akd:tileId>545554685</akd:tileId>
                        <akd:featureIdAndFlags>90636290</akd:featureIdAndFlags>
                        <akd:tail_offset_on_route>34000</akd:tail_offset_on_route>
                        <akd:arrival_offset_on_arc>14400</akd:arrival_offset_on_arc>
                    </akd:ArcKeyWithOffset>
                </akd:ArcsKeys>
            </ExtendedData>
        </Folder>

Notes:
 - <akd:tileId>, <akd:featureIdAndFlags>, and <akd:tail_offset_on_route> are required to be able to reconstruct an arc for a given map
 - <akd:arrival_offset_on_arc> is optional and only reported if it is non 0
