// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Handling Map Updates

== Status

Proposed

== Context

https://jira.tomtomgroup.com/browse/NAV-29359[Epic link]

The instruction engine reads arc information from the map via the
junction model.  The arc references from the route are stored in the
IterableArcBuffer, and the junction model accesses the arcs via
ArcKeyIterator.  The resulting instructions are stored in a buffer.
The instructions expose arc link IDs.

When a map update invalidates map information, we therefore have to
clear two structures that hold invalidated arc data: the
IterableArcBuffer, and the instruction buffer in the
InstructionProvider.

We should then receive more arc information from the route, at which
point we can regenerate the instructions.

It is acceptable to provide arcs with outdated link IDs to the user until
new instructions are available.  We have made clear to Audi, the only
consumers of the instruction arc link IDs, that they may refer to map versions that are not available
during map updates.  During map updates they should be aware of that limitation.
The instructions will be updated with new arc link IDs at some point after the map update has completed.

A map update might not update the region in which we are currently
navigating.  As things stand now the route will only send us updated
arc information if they decide that the current route really is
affected.

== Proposal

The OnboardTripGuidanceManager will subscribe to map update
notifications.  When the map service requests that clients release
their locks, the OnboardTripGuidanceManager will shut down the
instruction engine completely.  The arc buffer will also be cleared.
Only when the instruction engine thread has exited and shutdown is
confirmed will the release callback complete.

The current instruction buffer will not be cleared.  These
instructions will still be available to the triggering engine and we
will still generate audio text messages.  These components do not
require map access.

When the map service signals that a new map is available, the
OnboardTripGuidanceManager will re-subscribe as a RouteListener.  This
will cause an OnRoutesChanged and OnPathChanged callback to arrive within a short time.
This will cause instruction generation to restart just as if a new
route had been planned.

Immediately after the map update, the route may still refer to link
IDs in outdated region versions.  Therefore the versions need to be
recorded in the arc buffer, and the junction model must check that
these link IDs are valid when generating junctions.  If an invalid
link ID is reached, the instruction engine must shut down cleanly.  In
this case we must rely on the routing engine sending an updated route.

The routing engine must provide updated route data with OnPathChanged if any link ID on
the route forwards of the current car position has been invalidated.
Since different components of the NK2 system may have slightly
different views of the current car position, a margin will be built
into this calculation such that any link ID within 1km behind the
current car position is also cause for sending updated route data.
This provides a guarantee that the instruction engine can be restarted
after it decides to shut down.

The subscription to the route will move from the ArcBuffer to the OnboardTripGuidanceManager.
This is so that the OnboardTripGuidanceManager can treat new data from OnPathChanged
as a reason to restart instruction generation from the start.
It should shut down the instruction engine and clear the arc buffer.
Then it should refill the arc buffer from the route data and restart instruction generation.
In future we may have a use case where data arrives due to new tiles
being available.  In this case the arc buffer can be more intelligent,
noticing that only arc keys beyond the current contents have changed.
However this advanced functionality should wait until a concrete use case arrives.

Neither the InstructionEngine nor the OnboardTripGuidanceManager need
to hold a lock on the map, because we are ensuring that the
instruction engine will be shut down while map updates happen.

This approach is designed to ensure the InstructionEngine never has
invalid arc link IDs.  However we do rely on fairly complicated
interactions between other components to guarantee this.  Therefore we
should have automatic tests for the case where an invalid arc link ID is
present in the route.

== Requirements on Routing Service

* When a listener subscribes with AddListener, they must be called
  back with OnRoutesChanged giving the current route.  This should
  hold even if the listener subscribes after the route has already
  been planned.
* When executing map matching, the route should consider arcs up to
  1km behind the current car position along the route, as well as all
  arcs in front of the current car position.

== Design Views

This sequence diagram shows how the system responds to the map service
updating the map.  This example assumes that the route needs to
re-map-match the portion of the route in front of the current car
position (or perhaps within 1km of the CCP).

[plantuml, map-update-sequence, alt="Map Update Sequence Diagram"]
----

Participant MapService
Participant OnboardTripGuidanceManager
Participant ArcBuffer
Participant InstructionEngine
Participant Trip


MapService -> OnboardTripGuidanceManager : OnReleaseRequest
OnboardTripGuidanceManager -> InstructionEngine : delete
OnboardTripGuidanceManager -> ArcBuffer : delete
OnboardTripGuidanceManager -> Trip : RemoveListener
OnboardTripGuidanceManager -> MapService : OnReleaseRequest success
...
MapService -> OnboardTripGuidanceManager : OnMapAvailable
OnboardTripGuidanceManager -> MapService : OnMapAvailable success
OnboardTripGuidanceManager -> Trip : AddListener
...
Trip -> OnboardTripGuidanceManager : OnRoutesChanged
Trip -> OnboardTripGuidanceManager : OnPathChanged
OnboardTripGuidanceManager -> ArcBuffer : delete
OnboardTripGuidanceManager -> ArcBuffer : create
note right: some arcs still invalid
OnboardTripGuidanceManager -> InstructionEngine : create
OnboardTripGuidanceManager -> InstructionEngine : SetRouteIterator
...
InstructionEngine -> OnboardTripGuidanceManager : OnNextInstructionChanged
InstructionEngine -> OnboardTripGuidanceManager : finished
note right: shut down due to invalid arc
OnboardTripGuidanceManager -> ArcBuffer : delete
...
Trip -> OnboardTripGuidanceManager : OnRoutesChanged
Trip -> OnboardTripGuidanceManager : OnPathChanged
note right: now all the arcs are updated
OnboardTripGuidanceManager -> ArcBuffer : create
OnboardTripGuidanceManager -> InstructionEngine : create
OnboardTripGuidanceManager -> InstructionEngine : SetRouteIterator
...
InstructionEngine -> OnboardTripGuidanceManager : OnNextInstructionChanged

----

This proposal involves moving responsibility for responding to
OnRoutesChanged and OnPathChanged from the arc buffer to the
OnboardTripGuidanceManager.  This sequence diagram shows how routine
updates from the route will be handled.  Both OnRoutesChanged and
OnPathChanged will be handled the same way.

plantuml, sample-plantuml-diagram, alt="Ownership and reference relationships between components", width=1024, height=800]
----

Participant OnboardTripGuidanceManager
Participant ArcBuffer
Participant InstructionEngine
Participant Trip


Trip -> OnboardTripGuidanceManager : OnRoutesChanged
Trip -> OnboardTripGuidanceManager : OnPathChanged
OnboardTripGuidanceManager -> ArcBuffer : create
OnboardTripGuidanceManager -> InstructionEngine : create
OnboardTripGuidanceManager -> InstructionEngine : SetRouteIterator
...
InstructionEngine -> OnboardTripGuidanceManager : OnNextInstructionChanged

----


== Consequences

For a period after an update the client will hold instructions,
including arc link IDs, which are invalid for the new map.

There is no strong guarantee on how long it will take for fresh
instructions to be available.

There is no dependency between guidance and routing for the necessary
work.  Only existing APIs will be used.
