// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= LaneGuidanceProvider route abstraction

== Status

Accepted

== Context

In the https://jira.tomtomgroup.com/browse/NAV-8472[NAV-8472 "Simple Lane
Guidance" epic] LaneGuidanceProvider needs to know what are the arcs of the
route between two route offsets. This information is required so that it can
construct lane guidance scenario around a guidance instruction.

== Alternatives
=== Come up with a new route abstraction
==== Advantages:
- clean design that focuses only on the needs of LaneGuidanceProvider

==== Disadvantages:
- more code to maintain
- partial overlap of functionality with IterableArcBuffer
  (iteration over arcs of the route)

=== Use the IterableArcBuffer and IterableInterface
IterableArcBuffer is designed to lazy load arc keys from an asynchronous data source.
The current route from NEWHAVEN is fully evaluated when it is provided to
trip-onboard service, so this part of functionality is not useful for us.
However the IterableInterface of ArcKeys abstraction can be used to get ArcKeys
and route offsets.
See:
https://bitbucket.tomtomgroup.com/projects/NAVKIT2/repos/nk2-navigation-trip-onboardservice/browse/navigation-trip-onboardservice/src/guidance/iterable_arc_buffer.hpp?until=8d0ea4e0c7e957c8504f6c91347e756376d52af5&untilPath=navigation-trip-onboardservice%2Fsrc%2Fguidance%2Fiterable_arc_buffer.hpp[IterableArcBuffer]

==== Advantages:
- code reuse
- unified way to access route data for InstructionProvider
  and LaneGuidanceProvider in nk2-navigation-instruction-engine
  repository

==== Disadvantages:
- IterableArcBuffer contains future proof functionality like blocking arc key
  iterators that are not useful in the current NK2 design
- IterableArcBuffer has significant code and synchronization sequence complexity

== Decision

Use IterableArcBuffer. We hope that in future either NK2 will evolve to use the
future proof functionality or the future proof functionality will be removed
yielding less complex design.

== Consequences

- Higher chance of delivering NAV-8472 as there is less code to write.
