// Copyright (C) 2021 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= deployment of regression test data files

== Status

Proposal

== Context
Execution of regression test requires a set of input files to be provided containing the test routes, reference data output from instruction and tigger dumpers.
This document covers the deployment of those data file across of Guidance repos.

== Regression test data files
- .od files describing the test routes used in regression tests These files are used as input to BatchRouter to produce .kml's with polyline describing the
  route.
- .kml files with arc data These files are result of running of arc key dumper (trip-onboardservice repo) on .kml's that are coming from BatchRoute. They have
  arc information embedded that can be used in consequent steps of regression testing. These files can be considered rather stable across of regression test
  runs and only changed in case a route is added or a map is changed
- reference .kml files containing instructions and triggers These files are result of running instruction and trigger dumpers on .kml's with arcs. This set of
  files is generated each time we need to create/update the reference. Updating the reference can happen e.g. if we introduce changes to instruction engine that
  break the regression tests, but considered to be an improvement. This set is less "stable" than arc or .od data
- generated .kml files containing instruction or triggers These files are generated for each PR and checked against the reference set using CI scripting.


== Regression test data deployment
It is proposed to store all .od and arc .kml files in instruction engine repository.
Reference files for instruction comparison should also be stored there. Reference files for triggering engine
should be stored in the triggering engine repo.

== Directory structure
For .od and .kml's with arc in instruction engine repo:
1. .od files: navigation-instruction-engine / test / regression / od / <.od files>
2. .kml reference instruction files: navigation-instruction-engine / test / regression / reference / [map name] / <.kml files>
3. .kml reference trigger files: navigation-triggering-engine / test / regression / reference / [map name] / <.kml files>

The files from #2 and #3 reside in different repos, where #3 is an extension of #2 with trigger information.
These files should be kept in sync, meaning, when updating reference information for instruction engine
regression tests, we also need to update it for triggering engine regression tests.
This is not strictly necessary, but for a sake of keeping everything aligned, the procedures for it needs to be
implemented.

== Regression test data creation
There is a number of steps required to generate the reference data:

1. Based on .od files using BatchRouter .kml's with polyline should be generated. Those are intermediate files that do not need to be stored.

2. Using .kml's from #1 using trip-onboardservice repo InstructionDumper tool .kml's :

- build InstructionDumper:

  mkdir build
  cd build
  conan install -o navigation-trip-onboardservice:onboardtests=True -pr <platform> ..
  conan build ..

- run InstructionDumper on the set of .kml's from step #1 (e.g. for a sample U-turn in Berlin):

  ./InstructionDumper -a -p berlin_uturn.kml -o  berlin_uturn_ark.kml --map_path  ~/Workspaces/maps/HCP3_GER_41_20Q2_DD035_BERLIN_UR
  --keystore_path ~/bin/home/keystore.sqlite --keystore_password $NDS_DEFAULT_KEYSTORE_PASSWORD

Resulting files are intermediated and should not be stored persistently in the repo.

3. Using .kml's from step #2 (or previously generated reference files in case of reference set update),
reference files for instruction engine regression tests need to be generated. This is done from within
instruction-engine repos:

- build instruction_dumper (e.g. for a sample U-turn in Berlin):

  mkdir build
  cd build
  conan install .. -pr <platform>
  conan build ..

- run instruction_dumper build under build/bin to generate instruction engine regression test reference
  .kml's:

  ./instruction_dumper [-k berlin_uturn_ark.kml | -k berlin_uturn.kml] -o berlin_uturn.kml
    --map_path  ~/Workspaces/maps/HCP3_GER_41_20Q2_DD035_BERLIN_UR --keystore_path ~/bin/home/keystore.sqlite
    --keystore_password $NDS_DEFAULT_KEYSTORE_PASSWORD

4. Submit the files generated in step #3 under corresponding directory (see "Directory structure" above)
in instruction-engine repo.

5. For .kml's from step #4 a reference set for trigger engine should be generated using the corresponding
   commands. This is done from within triggering-engine repo:

6. Submit the files generated in step #3 under corresponding directory (see "Directory structure" above)
in triggering-engine repo.

- TBD

In case of map changes or new routes added the steps should be re-executed from step #1. In case of a
reference set update only step #3 - #6 need to be executed.
