// Copyright (C) 2022 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Support for data access flavor "online"

== Status

Implemented

== Context

As part of the epic https://jira.tomtomgroup.com/browse/NAV-15335[NAV-15335], we had the user story https://jira.tomtomgroup.com/browse/NAV-69711[NAV-69711 - Enable NIE to work with NKW flavour of map access]. The map access for NKW is what we now call "online flavor", and it differentiates a little from the generic flavor. The most important difference, when it comes to the instruction engine, is that the online flavor does not provide "junction view images" (JVI). The instruction engine fetches images for the junctions that have an associated signpost, therefore this feature has to be disabled whenever the engine is built for the NKW environment.

== Decision

The online flavor does not allow the compilation of any code that refers to the members of the class CJunctionViewImages, or a call to GetPublicInterface<CJunctionViewImages>. In order to contain the changes within the repository navigation-instruction-engine, we decided to disable the compilation of such code:

. Two macros are defined in the CMake files, that are exposed to the C-Preprocessor depending on the map access flavor. They are DATA_ACCESS_JVI_AVAILABLE and DATA_ACCESS_ONLINE.
. The portion of the junction model implementation that requires access to JVI has been moved to a template, which may only be compiled when the macro DATA_ACCESS_JVI_AVAILABLE is present. Unless the implementation relies on a dummy or mock map, in which case fake JVI data is present, and real code can and must be compiled and tested.
. The collaboration tests that use a real NDS map and cover the JVI feature no longer expect successful retrieval of JVI when DATA_ACCESS_JVI_AVAILABLE is not defined.
. The unit tests that crash due to bugs in online flavor of map access have been disabled when DATA_ACCESS_ONLINE is defined.

Other approaches, such as specializing templates for JVI in the map access components, have been considered. However, they were neither considered necessary nor better.

== Consequences

We now have support for the online flavor of map access, at the cost of a couple of template specializations for JVI.
The build with online flavor is enabled via the conan option "target=online".
