// Copyright (C) 2022 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Provide electric toll collection transponder availability to lane guidance provider

== Status
Proposed

== Context
For tollgates in Korea and Japan, some tollgate lanes only support toll payment by electric toll collection (ETC) transponder.
For the vehicles without ETC transponder, lane guidance should not recommend those ETC-transponder-only toll lanes. It is illegal for a vehicle without ETC transponder to enter the ETC-transponder-only toll lanes.
For the vehicles with ETC transponder, lane guidance should recommend toll lanes which can be paid by ETC transponder because it is usually faster to pay by ETC transponder than pay by cash.

== Problem
In order to let lane guidance recommend the correct lanes based on ETC transponder availability, the lane guidance provider needs to know whether the vehicle has an ETC transponder.

== Proposed Solution
 - Introduce a new class, VehicleAttributes, to hold the vehicle-related attributes. Currently, it only contains the ETC transponder availability.
 - Introduce a new method, SetVehicleAttributes(VehicleAttributes), to LaneGuidanceProvider.

The VehicleAttributes class can be extended to support HOV lane guidance if needed. For example, a new parameter number_of_passengers.

The new vehicle attributes will not directly trigger the lane guidance regenerating a new lane guidance scenario. It only affects the next generated lane guidance scenarios.
Because if the lane guidance scenario needs to be regenerated, the route should also be re-planned and the lane guidance scenario will be regenerated naturally. Lane guidance component does not need to handle the regeneration.
