// Copyright (C) 2022 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Tollgate lane guidance

== Status
Proposed

== Context
A tollgate has several toll lanes. Each toll lane can support various toll payment types.

Depending on whether a vehicle has electric toll collection (ETC) transponder, it may prefer different kinds of toll lanes. Lane guidance can recommend toll lanes based on that.

For the vehicles without ETC transponder, lane guidance should not recommend those ETC-transponder-only toll lanes. It is illegal for a vehicle without ETC transponder to enter the ETC-transponder-only toll lanes.

For the vehicles with ETC transponder, lane guidance should recommend toll lanes which can be paid by ETC transponder because it is usually faster to pay by ETC transponder than pay by cash.

== Problem
Lane guidance should recommend a sequence of lanes to enter the suitable toll lanes of the tollgate.

== Proposed Solution
=== Toll payment types utility
- If the vehicle has no ETC transponder and ETC transponder is the only payment type accepted at the lane, forbid the lane because the lane is illegal for the vehicle to enter.
- If the vehicle has ETC transponder and the lane can support ETC transponder toll payment type, prefer the lane.
- Otherwise, there is no preference for the lane.

=== Lane level router
- Encourage lane switching by a small bonus 1 when the vehicle is switching
* from non-preferred lane to preferred lane
* from forbidden lane to non-forbidden lane
- Penalize lane switching by a small penalty 1 when the vehicle is switching
* from preferred lane to non-preferred lane
* from non-forbidden lane to forbidden lane
- Give a large bonus 1000 to preferred lane
- Give a large penalty 1200 to forbidden lane
* This penalty is larger than the bonus for HOV lane. Because we should forbid the illegal lane even it's a preferred HOV lane.

=== Lane guidance builder
Adjust lane recommendation based on the vehicle ETC transponder availability and the lane toll payment types.

For all lanes in all segments, if the value returned from the toll payment types utility is

* Prefer, recommend the lane.
* Forbid, clear the recommendation for the lane.
* Otherwise, do nothing.

Some cases to consider:

- Sometimes a lane is preferred but it is not in the shortest path. We still recommend it otherwise the user may think this lane is forbidden.
- If all lanes are forbidden, lane level router still delivers some lane level routes with minimum cost (although the cost is very high). In this case, we still need to clear the recommendation for all lanes because they are illegal to the users.
* Note that this situation rarely happens. Because ETC-transponder-only toll roads will be avoided by routing engine. It happens only when routing engine can't avoid it. For example, the user plans a route to the destination on an ETC-transponder-only toll road.
