// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Detection of situations in motorways

== Status

Implemented

== Context

https://jira.tomtomgroup.com/browse/NAV-64045

We had to come up with rules for detecting situations in motorways, in which we generate instructions
for taking a fork, switching or exiting the motorway. The first instruction type that we implemented
for motorways was the exit, followed later by switch and then fork. The implementation for detection
such situations evolved in order to eliminate many bugs that have been uncovered during tests of the
HCP3 SOP1 release, and is now more or less stable.

== Decision

It is important to highlight that a road is considered a motorway when:
* The NDS attribute "motorway" of the link is set to true;
* OR the NDS attribute "controlled access" is set to true while the speed limit is >= 80 km/h.

The situations for instructions in the motorway are evaluated in the sequence they are presented below.

=== Detection of highway switch

The conditions below must be fulfilled:
* Incoming line on route must be a motorway.
* In the same line a signpost must be present.
* The signpost destination must belong to the route or to any alternative of it past the maneuver.
* The signpost indicates a single directional road number.
* This directional road number cannot be found among the road numbers of the incoming line.
* The route stays in a road with controlled access.

=== Detection of motorway exit

The conditions below must be fulfilled:
* Incoming line on route must be a motorway.
* In the same line a signpost must be present.
* The signpost destination must belong to the route or to any alternative of it past the maneuver.
* Route leads the driver to leave the controlled access road immediately or via a ramp.
* The incoming line is not a ramp OR the signpost junction has type exit.

=== Detection of motorway fork

The conditions below must be fulfilled:
* Incoming line on route must be a motorway.
* In the same line a signpost must be present.
* The signpost destination must belong to the route or to any alternative of it past the maneuver.
* The route stays in a road with controlled access.
AND:
* Signpost does not indicate a directional road number;
* OR signpost indicates several directional road numbers;
* OR incoming line has multiple road numbers;
* OR the road number from the incoming line and signpost are the same.

== Consequences

Practically every situation that a driver may come across in a motorway will be handled as
an exit, switch or fork. There are exceptional cases when the detection may fail though.
For example, when a signpost is missing, or when the map data gives road attributes that do
not suffice to qualify it as a motorway. In these cases, the situations is handled either
as a "city fork" or a regular turn.
