// Copyright (C) 2022 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Support glyph for fork and bear left/right

== Status

Proposal

== Context

There are UX requirements that glyph should depend on the junction's topology.
The glyph should show taken road and the closest *drivable* not taken road.

UX:

* https://confluence.tomtomgroup.com/pages/viewpage.action?pageId=952862760#NIE_011.1Bearleft/right-VariationsofBearInstruction[Bear instruction glyph]
* https://confluence.tomtomgroup.com/display/FlaminGO/NIE_013+-+Motorway+specific+instructions#NIE_013Motorwayspecificinstructions-HowForkGeometryisreflectedinthemanoeuvrearrow[Fork instruction glyph]

NOTE: Talked with Alexey, potentially the one more alternative road should be displayed for a trifurcation situation. Solution should be easily extended for this use case.

Related USs:

* https://jira.tomtomgroup.com/browse/NAV-65257[SPIKE Adr for glyph handling for bear/fork Instruction]
* https://jira.tomtomgroup.com/browse/NAV-70646[Bear instruction's glyph should reflect junction topology]
* https://jira.tomtomgroup.com/browse/NAV-62298[Fork instruction icon should reflect road geometry]


== Decision

The general theme is to design the NK2 API around actual use cases.

The idea is to extend API only with needed information.
The needed information is:

* angle/direction for taken road
* angle/direction for a closest drivable not taken road
* potential for trifurcation with one more drivable not taken road

That information will help to choose the correct asset in UI logic.

Proposal:

* Extend https://bitbucket.tomtomgroup.com/projects/NAVKIT2/repos/nk2-navigation-trip-clientlib/browse/navigation-trip-clientlib/include/tomtom/navkit2/guidance/turn.hpp[Turn class] with 2 more functions:

[source,cpp]
----
/**
 * Returns directions for the closest drivable alternative road.
 * Classification of the relative angle of the turn. This does not only depend
 * on angle in degrees, but is also adjusted based on other junction exits to disambiguate.
 */
Direction GetDirectionForClosestAlternativeRoad() const;

/**
 * Returns turn angle for the closest drivable alternative road relative to the entry road.
 * %Turn angle relative to the route in driving direction, in the range -179...180 degrees.
 * For example, -90 means "forks off to the left in a perpendicular angle".
 * At complex junctions, the angle is relative to the entry road.
 */
int32_t GetAngleInDegreesForClosestAlternativeRoad() const;
----

* Extend https://bitbucket.tomtomgroup.com/projects/NAVKIT2/repos/nk2-navigation-trip-clientlib/browse/navigation-trip-clientlib/include/tomtom/navkit2/guidance/fork.hpp[Fork class] with similar 4 functions and own Direction enum as in fork case the only directions will be: 'Slight left, Straight, Slight right'

[source,cpp]
----
/**
 * Classification of a relative turn angle.
 */
enum class TurnDirection {
    kStraight = 0,
    kSlightRight = 1,
    kSlightLeft = 2
};

/**
 * Classification of the relative angle of the turn. This does not only depend
 * on GetAngleInDegrees(), but is also adjusted based on other junction exits to disambiguate.
 */
TurnDirection GetDirection() const;

/**
 * %Turn angle relative to the route in driving direction, in the range -179...180 degrees.
 * For example, -90 means "forks off to the left in a perpendicular angle".
 * At complex junctions, the angle is relative to the entry road.
 */
std::int32_t GetAngleInDegrees() const;

/**
 * Returns directions for the closest drivable alternative road.
 * Classification of the relative angle of the turn. This does not only depend
 * on angle in degrees, but is also adjusted based on other junction exits to disambiguate.
 */
TurnDirection GetDirectionForClosestAlternativeRoad() const;

/**
 * Returns turn angle for the closest drivable alternative road relative to the entry road.
 * %Turn angle relative to the route in driving direction, in the range -179...180 degrees.
 * For example, -90 means "forks off to the left in a perpendicular angle".
 * At complex junctions, the angle is relative to the entry road.
 */
int32_t GetAngleInDegreesForClosestAlternativeRoad() const;
----

NOTE: The proposed API for 'Fork' class doesn't include case handling for a trifurcation. The reason is that case is really unlikely to be happen. Extend 'Fork' with returning a vector while leaving 'Turn' return just one value looks strange. Also it is strange to force client to handle vector of data when for now will contain one value not the best solution.

=== Rejected alternatives

==== Alternative B
The idea to provide the angle/directions to all roads at junction.

*Motivation to reject*: No needs to implement something similar to https://jira.tomtomgroup.com/browse/NAV-29014[Expose Junction side roads].

==== Alternative C
The idea to provide some enum of the road situation.

*Motivation to reject*: This approach is very tailored to the current UX spec and not very flexible or extendable.
