// Copyright (C) 2023 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Mini-roundabouts

== Status

Accepted

== Context

Mini roundabouts are roundabouts with a fully traversable central island or no central island. Examples can be found at
locations: (53.71738, -1.85718), (53.7162800, -1.8717860), (53.7195827, -1.8564723). Currently, mini-roundabouts are
treated as regular junctions. This behavior was reported as an https://jira.tomtomgroup.com/browse/DDAPP-14581[AmiGo bug].

https://confluence.tomtomgroup.com/display/AMF/Mini+Roundabouts+Orbis2NDS+implementation+options[The discussion] was
carried out to determine the proper approach for adding mini roundabouts handling. The solution of adding a new
"mini-roundabout" attribute in the attribution FTX was chosen. Attributes FTX is an FTX (fast track extension) building
block defined for the purpose of adding custom attributes to the map without updating the NDS version. In tasks:
https://jira.tomtomgroup.com/browse/OM2NDS-2219[Define Attributes FTX model for mini roundabouts] and
https://jira.tomtomgroup.com/browse/OM2NDS-2220[Fill Attributes FTX with mini roundabouts] mini-roundabout attribute was
added to NDS maps - FTX_SIMPLE_INTERSECTION_TYPE. The purpose of this ADR is to discuss the possibilities of adding
mini-roundabouts to the Navigation Instruction Engine.

== Problem

Currently, in the Navigation Instruction Engine, there is a roundabout handling that is based, among others, on the
geometry of roundabouts. Roundabouts are modeled by lines forming a roundabout object, in most cases, a circle.
Mini-roundabouts do not have a geometry. They are modeled as simple intersections, so the roundabout handling does not
work properly. Instead of roundabouts messages such as "Take the third exit," simple junction messages are produced,
such as "Turn left." There is a need for a solution that will support both types of roundabouts. A comparison of
roundabouts and mini-roundabouts handling can be found in the table below.

[options="header", cols="h,1,1"]
|===================
||Roundabouts| Mini-roundabouts
|Exit roads number calculation 2+|A number of outgoing routes from the roundabout.
|Exit angle calculation 2+|The angle change between the entry and exit point.
|Roundabout geometry|Lines formulate roundabout geometry.|It is a single point.
|Entry point - single-line entrance|The point where the entry route is connecting with the roundabout lines.|The point
on the entry route at a fixed distance from the center of the mini-roundabout (at the assumed radius of a
mini-roundabout; no actual data provided).
|Exit point - single-line exit|The point where the exit route is connecting with the roundabout lines.|The point on the
exit route at a fixed distance from the center of the mini-roundabout (at the assumed radius of a mini-roundabout; no
actual data provided).
|"V-shape" entrance/exit|The enter/exit points are calculated as a middle point between the arms of the "V-shape"
entrance.|Mini-roundabouts are modeled as a single point, so there are no "V-shape" entrances.
|U-turn logic|Based on the lines, formulating a roundabout and analysis of the entry and exit routes.|Based on the
analysis of the entry and exit routes.
|Driving direction|Driving direction is based on the driving directions of the lines formulating the roundabout.|
Driving direction is assumed as clockwise for the left-side traffic and counterclockwise for the right-side traffic.
When there is an exception from that, the NON_DEFAULT_TRAFFIC_SENSE FTX attribute should be present. Currently, it
doesn't work properly due to the problems on the Orbis side. See https://jira.tomtomgroup.com/browse/IM-39489[details].
|===================

== Alternative solutions

=== Alternative #1 - Extend roundabout_model_builder

In this solution, we propose extending roundabout_model_builder by adding handling for mini-roundabouts.

Pros:

* a lot of code can be reused due to the common part of roundabouts and mini-roundabouts handling,
* minimum implementation effort.

Cons:

* mixing special logic in one file,
* increased complexity,
* adding additional roundabout types (e.g., turbo roundabouts) would increase complexity even more.

See: https://github.com/tomtom-internal/navigation-instruction-engine/commit/b30422f6cecded0dfecc9afe6a72cc384c21897d[draft implementation.]

=== Alternative #2 - New mini_roundabout_model_builder

In this solution, we propose creating a new mini_roundabout_model_builder that contains mini-roundabout handling.

Pros:

* keep the original assumption in roundabout_model_builder,
* mini-roundabout logic in one place.

Cons:

* a lot of code will be duplicated,
* update in common logic for roundabouts and mini-roundabouts would have to be done in two files,
* adding additional roundabout types (e.g., turbo roundabouts) would lead to additional duplication.

See: https://github.com/tomtom-internal/navigation-instruction-engine/commit/96b7791895d2ee897c786b44f56792a7235e49a6[draft implementation.]

=== Alternative #3 - Inheritance

In this solution, we propose extracting common logic to base_roundabout_model_builder and keeping special logic in
normal_roundabout_model_builder and mini_roundabout_model_builder, which will inherit from base_roundabout_model_builder.

Pros:

* special logic is kept in individual builders to avoid increased complexity,
* common logic is kept in the base builder to avoid code duplication,
* additional roundabout types (e.g., turbo roundabouts) could inherit from base_roundabout_model_builder as well.

Cons:

* bigger implementation effort.

See: https://github.com/tomtom-internal/navigation-instruction-engine/commit/e3e2482995ddd8b2c83549eb7a1f382197451fea[draft implementation.]

== Proposal

Our proposition is to implement the #3 alternative. The solution does not increase the complexity of roundabout handling
and doesn't duplicate code.  It's open to adding other types of roundabouts. The only downside that we can see is a bigger
implementation effort and some refactorings needed.

== Consequences

As a consequence of adding mini-roundabouts handling to the Navigation Instruction Engine, drivers will get roundabout
instructions not only on regular roundabouts but also at mini-roundabouts, e.g., "Take the third exit" instead of
"Turn left."  Bugs related to the fact that mini-roundabouts are not treated like roundabouts, e.g.,
https://jira.tomtomgroup.com/browse/DDAPP-14581[DDAPP-14581] could be solved.
