// Copyright (C) 2023 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

= Motorway Guidance Glossary

== Motivation

The primary motivation behind creating this document is to establish a common ground for all involved parties (developers and the UX). +
By defining and clarifying the terms used throughout the project, we aim to foster clear communication, +
reduce ambiguities, and ensure that everyone is aligned in their understanding. +
This document should help us to take the first steps in resolving persistent motorway guidance issues. +

Origin of the document: https://confluence.tomtomgroup.com/x/Z12sR +

== List of terms

*Intersection* - is a point at which two or more roads cross or meet. +
From the developer's point of view, it's an NDS junction that has at least three outgoing arcs. +
Intersections are T-intersections, Y-intersections, forks, N-way intersections, and so on...

*Road situation* - is a route stretch at the junction where the instruction engine intentionally produces or suppresses the instruction. +
It's a pattern that consists of a set of rules. If rules are satisfied, then the road situation is detected. +
Road situations may have the same names as intersections where they appear (e.g. bifurcation).

IMPORTANT: It's possible to have different road situations at the same intersections depending on the route stretch. +
Let's analyze this intersection on the motorway as an example: +
https://www.google.com/maps/place/51%C2%B014'02.5%22N+6%C2%B042'29.6%22E/@51.2341682,6.7074442,167m/data=!3m1!1e3!4m4!3m3!8m2!3d51.2340359!4d6.7082125?entry=ttu +
This intersection type is a bifurcation since the road splits without interrupting the traffic flow. +
If the route goes through the right branch - then it's an exit road situation since it leads from a motorway to a non-motorway road: +
https://www.google.com/maps/dir/51.2334091,6.7115605/51.2361533,6.7032187/@51.2346495,6.7048156,725m/data=!3m1!1e3!4m2!4m1!3e0?entry=ttu +
If the route continues straight - it's a natural continuation situation since the driver does not need any instruction to pass through this intersection: +
https://www.google.com/maps/dir/51.2334091,6.7115605/51.2345804,6.7052171/@51.2338614,6.7071022,363m/data=!3m1!1e3!4m2!4m1!3e0?entry=ttu

This way, it's possible to have a natural continuation road situation at the bifurcation intersection type.

*Motorway* - is a road whose corresponding arc has either the _IsMotorway_ flag set to true +
or the _IsControlledAccess_ flag set to true and a specified minimum speed limit of 80 km/h.

*Fork* - is an intersection type where the road splits without interrupting the traffic flow.

*Bifurcation (intersection type)* - is a fork with two outgoing roads.

*Bifurcation (road situation)* - is a road situation that happens on bifurcations (intersection type) only +
and always requires a fork(left, right) instruction to take one of the two possible options.

*Trifurcation (intersection type)*  - is a fork with three outgoing roads.

*Trifurcation (road situation)* - is a road situation that happens on trifurcations (intersection type) only +
and always requires fork(left, middle, right) instruction to take one of the three possible options.

*Highway Switch* - is a road situation that happens on motorways and requires a special switch highway instruction +
to leave the current motorway (via exit or fork) in order to take another one.

*Exit* - is a road situation which happens at forks and requires special exit instruction to leave the current motorway.

*Natural Continuation* - is a group of road situations when the driver does not need any instruction to pass through the intersection and stay on the route.
