// Copyright (C) 2018 TomTom NV. All rights reserved.

= Continuous Lane Guidance Software Switch

== Context

Audi currently consumes lane guidance in two ways:

1. Simple Lane Guidance widget, which shows a schematic of the lane
configuration at the next upcoming instruction
2. ExitView, which shows a 3D stylised representation of the
configuration of lanes at and around the next upcoming instruction

They now would also like a third system that will indicate the correct
lane from the current car position up to 3km ahead.  Unlike the
previous two, this will always be present, independent on whether an
active driver maneuver must be performed within that 3km.  Therefore,
this will form https://jira.tomtomgroup.com/browse/NAV-143938[a
continuous sliding window of lane guidance].

The intended solution is to adapt the existing lane guidance API such
that it provides a series of overlapping lane guidance scenarios, such
that the latest scenario always includes at least 3km past the current
car position.

== Problem

This implementation bears many risks:

1. it might not perform adequately
2. there may be serious gaps due to information not being available
3. existing consumers may not be built to handle additional
information
4. existing consumers may not handle scenarios that may not contain
instructions

Many of these risks are outside TomTom's control.  Therefore we will
need to deliver prototypes of the new functionality for evaluation.
During this evaluation period we will still be delivering unrelated
improvements and bug fixes.  Therefore the new functionality cannot be
the default behaviour on mainline.  It must only be enabled during
evalution of this specific feature.

Our intention is to implement an additional implementation of
`LaneGuidanceProvider`, called `ContinuousLaneGuidanceProvider`.  Then
clients can control which will be used, perhaps by calling
`MakeContinuousLaneGuidanceProvider` instead of
`ContinuousLaneGuidanceProvider`.  However, this still doesn't address
the question of how downstream drive testers can access the
alternative lane guidance implementation.

== Software Switch

One option is to add a software switch that is controlled via the
configuration bundle.

This would require work by eSo to set the switch to the appropriate
value, so they can deliver an APK with continuous lane guidance for
testing that feature, and with normal lane guidance for testing any
other feature we deliver.

== Separate SDK delivery

Another option is to deliver a separate SDK based on a custom branch,
in which the default flag value is flipped to continuous lane
guidance.

We currently do not know if such delivery is possible.

= Decision

Assuming that there is no way to deliver a custom SDK, we will requrie
the software switch to be passed in the configuration bundle.
