// Copyright (C) 2024 TomTom NV. All rights reserved.

= Make Use of Accumulated Data to improve HOV Handling

== Status

Accepted

== Context

From the very beginning NIE was designed to be stateless, which imposed some
challenges and ultimately limitations for correct HOV handling.

Currently, each call to some HOV handler (`HovLaneHandler`,
`CompleteHovRoadEntranceHandler`, or `CompleteHovRoadExitHandler`)
has no knowledge about previously generated EnterHov or ExitHov instructions,
which is why these detectors may generate contradicting instructions, e.g.
ExitHov without preceeding EnterHov or multiple consecutive EnterHov
instructions.

These issues were solved by introducing `HovManeuverPostProcessor`` on
`InstructionProvider` level, that would cache HOV instructions and filter them
based on the heuristic that EnterHOV and ExitHOV instructions must alternate,
starting with an EnterHov instruction, assuming the driver is not on
HOV when he starts driving on the route (which might not be accurate, see
NAV-137179).

Despite this workaround, there are currently two customer tickets, stating that
ExitHov was given without preceding EnterHov: NAV-120461, NAV-135716. This is
due to the fact that there are occasions where HOV lanes just end, in which case
we are supposed to not give an ExitHov instruction at all. Because of this
missing ExitHov instruction, the postprocessor is not able to filter the
instructions correctly and confuses the next ExitHov instruction to be the one
associated with the last EnterHov instruction.

Recently, the assertion that the instruction engine must be stateless, was
relaxed and NAV-124311 introduced a generic concept called accumulated data,
which can be used to store state for the instruction handlers. This is what we
want to use to remove the HOV postprocessor and solve the two customer tickets.

== Proposal

In order to solve the mentioned problems, the handlers need to know if the
driver is already in HOV at the offset on route they are called on.

Accumulated data can be added AFTER each instruction generation increment,
based on the generated instructions in that increment and all the arcs that
have been consumed by that generation step.

For each EnterHov and ExitHov instruction we want to store offset on route and
the hov state starting from that offset; whether the driver is on HOV (after
EnterHov) or not on HOV (after ExitHov).

The driver might also leave HOV without an ExitHov instruction, which we solve
by additionally checking the arcs for a transition of complete or partial
carpool road to non-carpool road.

It was already observed that just checking for a singular transition results
in false positives, because of wrong attributions in the map data. Thus we
plan to interpret such a transition as the driver having left HOV only if the
stretch of non-carpool thereafter is longer than a certain threshold (1km).

== Proposal Extension Idea

Additionally to the mentioned problems, specially the `HovLaneHandler` has the
big disadvantage to have to look far ahead in order to create instructions.
Thus one idea is to incrementally store relevant segment and arc information
inside the accumulated state.

The HOV handler would then use this "window to the past" to create instructions
for the present offset along the route. It would probably still have to look a
bit ahead for verifying certain conditions, but this lookahead would be much
smaller.

This can be seen as an extension to the aforementioned proposal, as we still
need to add the detections into the accumulated state even for that approach.

For this extension we would have to serialize a lot of data, which could affect
runtime performance. Moreover it requires a complete rewrite of the hov
detectors, which would be a huge effort and is quite risky given the current
state of the project. It is also much harder to test this, because the
accumulated state that would need to be simulated is huge.

== Decision

Just implement the first proposal and leave the extension for later if it is
needed at all.
