// Copyright (C) 2024 TomTom NV. All rights reserved.

= Confirmation timing improvement based on administrative road class

== Status

Proposal

== Context

Currently, the triggering timing is based on region, road types (motorway, city or rural roads) and instruction types.

Now there are feedback from HCP3.

* For rural roads with inner-city speed limits (lower importance road), the confirmation phase voice guidance should be played later. More details can be seen https://jira.tomtomgroup.com/browse/GOSDK-27395[here].
* For urban roads with higher inner city road class, the confirmation phase voice guidance should be played earlier. More details can be seen https://jira.tomtomgroup.com/browse/GOSDK-21437[here].

== Problem

NIE does not expose a road attributes for the Triggering Engine (NK2) and the Guidance Triggering (GO SDK) to determine the triggering timing based on the importance of roads.

== Decision

NIE will expose administrative road class to the Triggering Engine (NK2) and the Guidance Triggering (GO SDK).
Specifically, in https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/navigation-instruction-engine/include/tomtom/navkit2/instruction_engine/instruction/road_information.hpp[RoadInformation],
```
struct RoadInformation {
    ...
   /**
    * The administrative road class of the road.
    * It is ranged in [0,6], where 0 is the most important road and 6 is the least important road.
    * boost::none if the administrative road class is not available.
    */
    boost::optional<unsigned int> administrative_road_class;
    ...
};
```

`RoadInformation` is provided for incoming and outgoing roads of instructions.
It is an existing API.
