// Copyright (C) 2020 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

[[section-introduction-and-goals]]
== Introduction and goals

Instruction engine is a software component that generates turn by turn instructions for safely
navigating the users towards their destination.

=== The old instruction engine
The onboard system NavKit1 as well the NKW Online Routing service provide turn-by-turn instructions
for routes.  Both systems use the legacy instruction engine for that. The legacy instruction engine
is hard to maintain, hard to extend, does not follow UX-driven concepts, and its complexity gives
rise to bugs regularly.

=== The new instruction engine
The New Instruction Engine (NIE) will be a modern, powerful instruction engine that will power our
next-generation stack onboard and in the cloud and deliver a solid, no-stress and delightful driving
experience. It will enable the faster, inexpensive development and turnaround cycle, and the
adaptability that our customers require and that cannot be reached with the old codebase.

NIE will initially be deployed as part of the onboard NK2 system and will be limited by the
current capabilities and data that NK2 provides. Over the time these capabilities will be expanded
to match the quality and scope of the old instruction engine. This includes replacing the NKW
solution with NIE based online instruction generation system.

Instruction engine will be discussed in the document:

* _Instruction engine_ - responsible for generating turn by turn instructions

[[requirements]]
== Requirements overview

=== Instruction types
* Simple turn instructions
* Simple roundabout instructions
* Highway bifurcations and trifurcations
* Complex roundabouts
* Complex intersections
* Arrivals and waypoints
* Decision points
* Follow lane instructions

=== Instruction data
* plain text representation of the instruction
* names (street, city, country, intersection)
* signposts
* sideroads
* landmarks
* prerecorded audio clips

=== Features of the system beyond parity with NavKit1
These features are not fully scoped yet, rather they provide an idea what may be required from the system in the future.

* configurability
** have a different verbosity for manual and autonomus mode
** have adjustable guidance for different devicves/vehicles/modes
** have a different guidance in different regions/users
** customise guidance base on country/user
* personalization
** provide minimum set of info and refine upon uncertanty
** distinguish known and unknown routes
** react to user's mood
** adapt to different cultures of driving
** adjust verbosity for known/unknown routes
** customise instructions based on how familiar the driver is with the route
* dynamic lane guidance
* landmark guidance
* natural guidance

[[section-quality-goals]]
== Quality goals
The most important quality goals affecting the architecture are:

.Quality goals
[cols="1,5,10,10", grid="rows", frame="topbot", options="header"]
|==============================================================
| | Quality goal | Description | Business motivation

| {counter:qualitygoal}
| UX-driven
| The behavior of the guidance engine shall be driven by well understood
UX specifications.
| Following a UX spec should blend the guidance engine behavior seamlessly into the
rest of the navigation system.

| {counter:qualitygoal}
| Extensibility
| The guidance engine shall be easily extendable with new instructions,
new (audio) messages, data attributes etc.
| New customers, new markets, or new navigation trends require to regularly
extend the behavior of the guidance experience.

| {counter:qualitygoal}
| Testability
| The need for manual testing should be reduced to the absolute minimum, but exploratory
and drive testing should be possible at any time.
| High testability increases the confidence in the quality of the guidance experience, and
reduces the risks of functional extensions. The required tools should be developed early on
in the project so we can find out which parts of automated tests are missing.

| {counter:qualitygoal}
| Modularity
| The building blocks of the NIE should be self-contained and
where possible easy to understand in isolation.
| The architecture should allow automated functional testing of components in
isolation so that issues can be recognised and the appropriate module can be
identified quickly

| {counter:qualitygoal}
| Explainability
| The guidance engine shall be explainable to key stakeholders: customers, users, product managers, developers.
a|
* Customers often request to get an explanation for:
** the principal philosophy of the guidance experience ("Is it possible to be guided just by audio?")
** specific behavior ("When do you say _Keep Left_?")
* Users often desire a predictable behavior that they understand ("Why is there an instruction here, but not there?")
* Product managers often require to communicate the (potential) capabilities
("Why is adding a street name easy, but a road number hard?"
* Developers often need to explain a certain behavior _post mortem_, e.g., in
a bug report.

| {counter:qualitygoal}
| Data efficiency
| NIE must respect the network bandwidth requirements imposed by products that integrate it (NK2, GoSDK).
| The system must be able to work in online environments with restricted network bandwidth and restricted disk space.
  Efficient utlilization of bandwidth is a prerequisite that enables this goal.

| {counter:qualitygoal}
| Robustness
| In case of errors in data or restrictions in data the system must degrade gracefully.
| When running without the onboard map the system must take into consideration that not all
  necessary data for instruction generation may be available. In worst case important parts of the map may
  be missing due to loss of connectivity. The system should handle such degradations gracefully. Graceful
  degradation means providing an alternative version of your functionality or making the user aware of
  shortcomings of a product as a safety measure to ensure that the product is usable.
  One example of such situation is in NK2 where the initially available LaneFTX tiles may not be available for the
  update region where the car is located and will only become available after the first map update is
  received for this update region. In such cases instruction engine should have fallback heuristics to
  operate on data available in routing and guidance building block.

| {counter:qualitygoal}
| Latency
| _Instruction Engine_ should meet latency expectation of modern embedded applications.
| An important KPI to take into consideration is the _time to first guidance_. This KPI measures how much time
  passes from the moment the user inputs the route parameters to the first complete turn by turn guidance
  information being delivered.

|==============================================================




The full set of quality attributes and their validation scenarios can be found
in <<section-quality-scenarios>>.
