// Copyright (C) 2023 TomTom NV. All rights reserved.

[[section-delivery-pipeline]]
== Delivery pipeline

https://docs.github.com/en/actions[GitHub Actions] is used to automate the Delivery Pipeline.
This document describes how Continuous Integration and Continuous Delivery are implemented.

=== Continuous Integration

The https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/.github/workflows/pr-verification.yaml[Pull Request Verification workflow] facilitates Continuous Integration.
As contributions to Instruction Engine are expected through pull requests, this workflow is run in context of pull requests.

[plantuml, continuous-integration, alt="Continuous Integration"]
....
@startuml

start

:quality checks;
if (essential files changes?) then (yes)
split
  :Conan package verification;
split again
  :Create doxygen\ndocumentation;
end split
else (no)
endif

  :conclusion;
stop

@enduml
....

[options="header]
|======
| Building block | description

| Quality checks
| Facilitated by https://github.com/tomtom-internal/conan-reusable-workflows/blob/main/docs/workflows/quality-checks.adoc[the reusable quality checks workflow], run various "quick" checks.

| Conan package verification
| Facilitated by https://github.com/tomtom-internal/conan-reusable-workflows/blob/main/docs/workflows/conan-package-verification.adoc[the reusable Conan package verification workflow], run i.a. several quality checks, an OSS compliance scan, a Sonarqube scan, builds.
This workflow is configured through https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/.github/workflow-config.yaml[the workflow configuration file].
The behavior of this workflow (specifically the nested https://github.com/tomtom-internal/conan-reusable-workflows/blob/main/docs/workflows/conan-package-matrix-build.adoc[Conan package matrix build workflow]) is extended through pre and post steps defined https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/.github/reusable-workflows-extensions[here].

| Create doxygen documentation
| Facilitated by https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/.github/workflows/doxygen.yaml[the doxygen workflow], doxygen documentation is generated.

| Conclusion
| This is an overall fan-in job that is configured as a required status check in the default branch' protection rules.
It is facilitated by https://github.com/tomtom-internal/conan-reusable-workflows/blob/main/.github/workflows/conclusion.yaml[the reusable conclusion workflow].

|======

=== Continuous Delivery

A new version of the Instruction Engine is considered delivered when its Conan recipe and associated packages are uploaded to Artifactory.
As the Instruction Engine is consumed internally (e.g. by routing API and GoSDK), delivery in this context implies available for internal usage.
The https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/.github/workflows/release.yaml[Release workflow] facilitates Continuous Delivery and is run when commits are pushed to https://github.com/tomtom-internal/navigation-instruction-engine/tree/main[the main branch].

[plantuml, continuous-delivery, alt="Continuous Delivery"]
....
@startuml

start
:Conan package release;
if (new version?) then (yes)
split
  :Create and upload\nDoxygen documentation;
split again
  :Update architecture\ndocumentation;
end split
else (no)
endif
  :conclusion;
stop

@enduml
....

[options="header]
|======
| Building block | description

| Conan package release
a| Facilitated by https://github.com/tomtom-internal/conan-reusable-workflows/blob/main/docs/workflows/conan-package-release.adoc[the reusable Conan package release workflow], bump version, run an OSS compliance scan, a Sonarqube scan a Coverity scans and builds.
This workflow is configured through https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/.github/workflow-config.yaml[the workflow configuration file].
The behavior of this workflow (specifically the nested https://github.com/tomtom-internal/conan-reusable-workflows/blob/main/docs/workflows/conan-package-matrix-build.adoc[Conan package matrix build workflow]) is extended through pre and post steps defined https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/.github/reusable-workflows-extensions[here].

When version is bumped (based on the conventional commits) and successful, it publishes the new version of the Conan recipe and associated binaries to https://artifactory.tomtomgroup.com/[Artifactory].
Specifically they're uploaded to the https://artifactory.tomtomgroup.com/ui/repos/tree/General/navkit2-conan-local/[navkit2-conan-local] (note; this repository is not specific to navkit2, its name is merely a leftover from that era) over https://artifactory.tomtomgroup.com/ui/repos/tree/General/navkit2-conan-local/tomtom/navigation-instruction-engine[here].

| Create and upload Doxygen documentation
| Facilitated by https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/.github/workflows/doxygen.yaml[the doxygen workflow], doxygen documentation is generated.
Generated documentation is uploaded to https://artifactory.tomtomgroup.com/[Artifactory], specifically over
https://artifactory.tomtomgroup.com/ui/repos/tree/General/navkit2-docs/navigation-instruction-engine[here].

| Update architecture documentation
| Facilitated by https://github.com/tomtom-internal/navigation-instruction-engine/blob/main/.github/workflows/asciidoc-to-gh-pages.yaml[the AsciiDoc to GitHub Pages workflow] regenerate the architecture documentation based on https://github.com/tomtom-internal/navigation-instruction-engine/tree/main/documentation/architecture[source], uploads the result as a workflow run artifact and updates https://tomtom-internal.github.io/navigation-instruction-engine[this page] accordingly.

| Conclusion
| This is an overall fan-in job that is facilitated by https://github.com/tomtom-internal/conan-reusable-workflows/blob/main/.github/workflows/conclusion.yaml[the reusable conclusion workflow].
|======
