// Copyright (C) 2018 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

[[section-technical-risks]]
== Risks and technical debts

=== New Instruction Engine
==== A lot of global field testing required
Instructions have to be different for various parts of the world, as customer
requirements can also different per region.

To mitigate this risk, we have to plan intensive field testing towards the end
of our development phase and make sure that we extract region specific tweaks
from the original source code.

==== No clear quality measure available
There is no straight forward measurement for instruction quality.

What we need is good UX specifications upfront and extensive field testing.

==== Performance decrease
The performance (time and memory spent for computing an instruction)  may not
match the performance of the old engine.

The risk of this is not very high and can be mitigated by making KPIs an early
part of the development process.

==== Scope creep
There are a lot of requests for new features and possibly 3 products to support
(NavKit 1.0, NavKit 2.0, NKW Routing).

We should make conscious choices about which products to integrate the engine
into and not aim to serve all products at the same time.

==== Early architectural decisions may impact product quality
In NavKit1 an architectural decision to collapse junctions to a single point prevents us from
generating good quality of instructions. Refactoring this mistake would equal in effort to writing
a new engine from scratch.

To avoid this in the _NIE_ we propose to tackle complicated scenarios very early in the development
cycle. For us this means adding support for special traffic features like michigan left and
hamburger roundabout.
