// Copyright (C) 2020 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

[[section-introduction-and-goals]]
== Introduction and goals

The Junction Model is a component of the Instruction Engine
architecture.  It provides an abstraction layer between the direct map
access layer more suited to the instruction engine.

=== Hides Unnecessary Details

The data access layer exposes a large surface area including many
details unnecessary for the instruction engine.  The JunctionModel
hides those irrelevant details from the instruction engine, making it
easier to reason about how the instruction engine interacts with
the map.

From the other side, the junction model clarifies which features of
the map are used by the instruction engine, making it easier to reason
about how the instruction engine affects the overall architecture.

=== Object-Oriented Interface

The data access layer has a functional interface style.  To retrieve
information about a node or arc, you call a member function of the map
with the node or arc as an argument.  For example:

`map_data_.IsRightHandDriving(arc_);`

The junction model exposes an object-oriented view more natural for
the instruction engine:

`line->IsRightHandDriving();`

=== Support Onboard Map and Tile Cache

The long-term plan for the instruction engine is that it should be
suitable for use both with onboard maps and with a tile cache of an
online map.  Initially it was developed for the tile cache.  Later
development focus switched to onboard maps.  The two both use a data
access layer, but while the two are very similar there are small
differences.  The junction model hides those differences, allowing a
single instruction engine implementation to work with both.
