name: Export UX Spec to PDF

on:
  workflow_dispatch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin zip
          # Install Node.js
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          # Install mdpdf
          npm install -g mdpdf

      - name: Update links in Markdown files
        run: |
          # Replace links pointing to .md files with .pdf equivalents
          for INPUT_FILE in $(find . -name "*.md"); do
            echo "Updating links in $INPUT_FILE"
            sed -i 's|\]\(([^()]*)\.md\)|](\1.pdf)|g' "$INPUT_FILE"
          done

      - name: Convert Markdown to PDF
        run: |
          OUTPUT_DIR="nie_ux_spec"
          mkdir -p "$OUTPUT_DIR"
          
          for INPUT_FILE in $(find . -name "*.md" ! -name "README.md"); do
             echo "Processing file: $INPUT_FILE"
             OUTPUT_FILE="${INPUT_FILE%.md}.pdf"
             mdpdf "$INPUT_FILE" && mv "$OUTPUT_FILE" "$OUTPUT_DIR/"
             echo "Conversion of $INPUT_FILE completed. Output file: $OUTPUT_FILE"
          done
          
          zip -r "nie_ux_spec.zip" "$OUTPUT_DIR"

      - name: Upload PDF ZIP
        uses: actions/upload-artifact@v4
        with:
          name: nie_ux_spec
          path: nie_ux_spec.zip
