name: Export UX Spec to PDF

on:
  workflow_dispatch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin zip python3-pip
          # Install Node.js
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          # Install mdpdf
          npm install -g mdpdf


      - name: Update Markdown Links to PDF
        run: |
          echo "Updating Markdown links to PDF..."
          python3 .github/workflows/update_links.py

      - name: Convert Markdown to PDF
        run: |
          echo "Converting Markdown files to PDFs..."
          INPUT_DIR="."
          OUTPUT_DIR="output"
          
          mkdir -p "$OUTPUT_DIR"
          
          find "$INPUT_DIR" -name "*.md" ! -name "README.md" | while read -r INPUT_FILE; do
              RELATIVE_PATH=$(dirname "${INPUT_FILE#./}")
              mkdir -p "$OUTPUT_DIR/$RELATIVE_PATH"
          
              OUTPUT_FILE="$OUTPUT_DIR/${INPUT_FILE%.md}.pdf"
              mdpdf --timeout 120000 "$INPUT_FILE" -o "$OUTPUT_FILE"
              echo "Converted $INPUT_FILE to $OUTPUT_FILE"
          done
          
          # Create ZIP file with all PDFs
          zip -r "${OUTPUT_DIR}.zip" "$OUTPUT_DIR"

      - name: Upload PDF ZIP
        uses: actions/upload-artifact@v4
        with:
          name: nie_ux_spec
          path: output.zip
