name: Export UX Spec to PDF

on:
  workflow_dispatch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install markdown

      - name: Generate HTML from Markdown
        run: python3 .github/workflow_scripts/generate_html.py "${{ inputs.src_dir }}" "${{ inputs.build_dir }}"

      - name: Fix ownership of HTML files
        run: sudo chown -hR "$(id -un):$(id -gn)"  "${{ inputs.build_dir }}"

      - name: Copy assets
        run: rsync -akv --exclude='.*' --exclude='**/*.md' "${{ inputs.src_dir }}"/ "${{ inputs.build_dir }}"/

      - name: Upload PDF ZIP
        uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.build_dir }}"
          path: output.zip
