# Copyright (C) 2022 TomTom NV. All rights reserved.

---

name: Deploy ux spec to GitHub Pages and SharePoint
# GitHub Pages will be available at: https://fluffy-train-v716q7o.pages.github.io/
# Drive link: https://tomtominternational.sharepoint.com/sites/nav-dx-guidance/Shared%20Documents/nie-ux-spec/

on:
  workflow_call:
    inputs:
      src_dir:
        description: root of path of Markdown files to recursively build HTML from
        required: true
        type: string
      build_dir:
        description: root of path to recursively publish static HTML from
        required: true
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-ux-spec:
    name: Deploy ux spec to GitHub Pages and SharePoint
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip Files
        run: zip -r archive.zip .

      # Add your build and other necessary steps here

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.event.release.tag_name }}
          body: |
            Description of the release
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./archive.zip
          asset_name: archive.zip
          asset_content_type: application/zip

