# Copyright (C) 2022 TomTom NV. All rights reserved.

---

name: Deploy ux spec to GitHub Pages and SharePoint
# GitHub Pages will be available at: https://fluffy-train-v716q7o.pages.github.io/
# Drive link: https://tomtominternational.sharepoint.com/sites/nav-dx-guidance/Shared%20Documents/nie-ux-spec/

on:
  workflow_call:
    inputs:
      src_dir:
        description: root of path of Markdown files to recursively build HTML from
        required: true
        type: string
      build_dir:
        description: root of path to recursively publish static HTML from
        required: true
        type: string
      bump-version:
          description: "whether or not to bump version based on Conventional Commits"
          type: boolean
          required: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-ux-spec:
    name: Deploy ux spec to GitHub Pages and SharePoint
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: bump version
        id: bump_version
        uses: tomtom-international/commisery-action/bump@v3
        if: inputs.bump-version
        with:
          token: ${{ github.token }}
          create-release: true

      - name: Print bump version output
        run:
            |
            echo "Bump version output: ${{ steps.bump_version.outputs.next-version }}"
            echo "Bump version output: ${{ steps.bump_version.outputs.current-version }}"

      # Add your build and other necessary steps here

    #  - name: Create Release
     #   id: create_release
      #  uses: softprops/action-gh-release@v1
       # with:
        #  tag_name: v${{ github.run_number }}
         # release_name: Release ${{ github.run_number }}
          #body: |
           # Changes in this release:
            #- Updated source code.
     #   env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


