name: Export UX Spec to PDF

on:
  workflow_dispatch

jobs:
  convert:
    runs-on: az-weu-ubuntu-20.04-amd64-05cpu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin zip
          # Install Node.js
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          # Install mdpdf
          npm install -g mdpdf

      - name: Convert Markdown to PDF
        run: |
          OUTPUT_DIR="nie_ux_spec"
          mkdir -p "$OUTPUT_DIR"
          
          find . -name "*.md" ! -name "README.md" ! -name "pull_request_template.md" | while IFS= read -r INPUT_FILE; do
            BASENAME=$(basename "$INPUT_FILE" .md)
            OUTPUT_FILE="${BASENAME}.pdf"
            mdfpdf "$INPUT_FILE" -o "$OUTPUT_FILE" && mv "$OUTPUT_FILE" "$OUTPUT_DIR/"
            echo "Conversion of $INPUT_FILE completed. Output file: $OUTPUT_FILE"
          done
          
           zip -r "nie_ux_spec.zip" "$OUTPUT_DIR"

      - name: Upload PDF ZIP
        uses: actions/upload-artifact@v4
        with:
          name: nie_ux_spec
          path: nie_ux_spec.zip