name: Upload ZIP Archive to Confluence

on:
  workflow_dispatch:

jobs:
  upload_to_confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload to Confluence
        env:
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
          PAGE_ID: '409764067'
          CONFLUENCE_URL: 'https://tomtom.atlassian.net/wiki/rest/api/content/'
        run: |
          # Upload the ZIP file from the repository
          curl -u "$CONFLUENCE_USER:$CONFLUENCE_TOKEN" -X POST "$CONFLUENCE_URL/$PAGE_ID/child/attachment" \
              -H 'X-Atlassian-Token: no-check' \
              -F "file=./archive.zip" \
              -H 'Content-Type: application/zip'
