name: Upload ZIP Archive to Confluence

on:
  workflow_dispatch:

jobs:
  upload_to_confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload to Confluence
        id: upload
        env:
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
          PAGE_ID: '409764067'
          CONFLUENCE_URL: 'https://tomtom.atlassian.net/wiki/rest/api/content/'
        run: |
            curl -u "${CONFLUENCE_USERNAME}:${CONFLUENCE_API_TOKEN}" \
                 -F "file=archive.zip" \
                 "${CONFLUENCE_URL}/rest/api/content/{PAGE_ID}/child/attachment"
          
      - name: Verify ZIP Upload
        env:
          CONFLUENCE_URL: 'https://tomtom.atlassian.net/wiki/rest/api/content/'
          PAGE_ID: '409764067'
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
        run: |
          response=$(curl -s -u "${CONFLUENCE_USER}:${CONFLUENCE_TOKEN}" \
                          "${CONFLUENCE_URL}/rest/api/content/{PAGE_ID}/child/attachment")
          echo "Response: $response"
          if echo "$response" | grep -q "archive.zip"; then
            echo "ZIP archive is successfully uploaded!"
          else
            echo "ZIP archive not found!"
            exit 1
          fi
