on:
  workflow_call:
    inputs:
      src_dir:
        description: root of path of Markdown files to recursively build HTML from
        required: true
        type: string
      build_dir:
        description: root of path to recursively publish static HTML from
        required: true
        type: string
      build_dir2:
        description: root of path to recursively publish static HTML from
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy Markdown to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Update Markdown Links
        run: |
          find "${{ inputs.src_dir }}" -name "*.md" | while read -r file; do
            sed -i 's|\(]\(.*\)(\.\*\)\.md|]\2.pdf|g' "$file"
          done

      - name: Install LaTeX packages
        run: sudo apt-get install texlive-xetex

      - name: Convert Markdown to PDF
        run: |
            find "${{ inputs.src_dir }}" -name "*.md" | while read -r file; do
              output_dir="pdfs/$(dirname "$file" | sed "s|${{ inputs.src_dir }}/||")"
              mkdir -p "$output_dir"
              output_file="$output_dir/$(basename "$file" .md).pdf"
              pandoc -s "$file" -o "$output_file" --pdf-engine=xelatex
            done

      - name: Archive PDFs
        uses: actions/upload-artifact@v3
        with:
          name: pdf-artifacts
          path: pdfs
