# Copyright (C) 2022 TomTom NV. All rights reserved.

---

name: Deploy Markdown to GitHub Pages
# Publishes to: http://username.github.io/repository.
# Docs: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow
# To enable gh-pages: https://pages.github.com/
#   goto:
#    - repo settings
#    - Pages
#    - Build and deployment -> Source: select GitHub Actions

on:
  workflow_call:
    inputs:
      src_dir:
        description: root of path of Markdown files to recursively build HTML from
        required: true
        type: string
      build_dir:
        description: root of path to recursively publish static HTML from
        required: true
        type: string
      build_dir2:
        description: root of path to recursively publish static HTML from
        required: true
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy Markdown to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build
        uses: docascod/actions-build@1.0
        with:
          sources: '*.md'
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          path: build/*.pdf

