on:
  workflow_call:
    inputs:
      src_dir:
        description: root of path of Markdown files to recursively build HTML from
        required: true
        type: string
      build_dir:
        description: root of path to recursively publish static HTML from
        required: true
        type: string
      build_dir2:
        description: root of path to recursively publish static HTML from
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy Markdown to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert Markdown to PDF
        run: |
          mkdir pdfs
          find "${{ inputs.src_dir }}" -name "*.md" -exec pandoc -s {} -o "pdfs/$(basename {} .md).pdf" --pdf-engine=xelatex \;


      - name: Archive PDFs
        uses: actions/upload-artifact@v3
        with:
          name: pdf-artifacts
          path: pdfs/*.pdf
