# Copyright (C) 2022 TomTom NV. All rights reserved.

---

name: Deploy Markdown to GitHub Pages
# Publishes to: http://username.github.io/repository.
# Docs: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow
# To enable gh-pages: https://pages.github.com/
#   goto:
#    - repo settings
#    - Pages
#    - Build and deployment -> Source: select GitHub Actions

on:
  workflow_call:
    inputs:
      src_dir:
        description: root of path of Markdown files to recursively build HTML from
        required: true
        type: string
      build_dir:
        description: root of path to recursively publish static HTML from
        required: true
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy Markdown to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install markdown

      - name: Generate HTML from Markdown
        run: python3 .github/workflow_scripts/generate_html.py "${{ inputs.src_dir }}" "${{ inputs.build_dir }}"

      - name: Fix ownership of HTML files
        run: sudo chown -hR "$(id -un):$(id -gn)"  "${{ inputs.build_dir }}"

      - name: Copy assets
        run: rsync -akv --exclude='.*' --exclude='**/*.md' "${{ inputs.src_dir }}"/ "${{ inputs.build_dir }}"/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ inputs.build_dir }}"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Install wkhtmltopdf and required dependencies
      - name: Install wkhtmltopdf and Qt libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          sudo apt-get install -y libxrender1 libxext6 libfreetype6 libfontconfig1


      - name: Convert HTML to PDF
        run: |
          mkdir -p pdf_output  # Kreirajte direktorijum pre nego što počnete sa konverzijom

          echo "Listing HTML files in ${{ inputs.build_dir }}..."
          find "${{ inputs.build_dir }}" -type f -name "*.html" | while read html_file; do
            echo "From: $html_file"
            output_pdf="pdf_output/$(basename "$html_file" .html).pdf"
            echo "To: $output_pdf"
            wkhtmltopdf --enable-local-file-access --load-error-handling ignore --debug-javascript "$html_file" "$output_pdf"
            echo "Finshed!"
          done


      # Create a zip archive of PDFs
      - name: Create a zip archive of PDFs
        run: |
          pdf_output_dir="pdf_output"
          zip_output="pdf_output.zip"
          echo "Zipping PDF files from $pdf_output_dir into $zip_output"
          zip -r "$zip_output" "$pdf_output_dir"

      # Verify that the ZIP file exists
      - name: List files to verify ZIP file
        run: |
          ls -lh "pdf_output.zip"

      # Upload the ZIP file as an artifact
      - name: Upload PDF ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf-files
          path: "pdf_output.zip"
