# Copyright (C) 2023 TomTom NV. All rights reserved.

---

name: Check pull request title

on:
  pull_request:
    # list of default types plus 'edited'
    types: [opened, edited, synchronize, reopened]
    branches:
      - main

  # commisery-action doesn't support merge queue (yet) and will silently exit if not run in context
  # of a pull request. Given we ensure PR titles are valid _and_ the commits in the merge queue
  # use the PR title as commit subject, checking the commits in the queue would be redundant.
  # However, we still run pr-title-check here to ensure the required status check is green.
  merge_group:

jobs:
  pr-title-check:
    uses: tomtom-internal/conan-reusable-workflows/.github/workflows/pr-title-check.yaml@1046c8d8e58b5a5253b06be914e013276040c6b6 # v2.1.4