# Copyright (C) 2023 TomTom NV. All rights reserved.

---

name: Release

on:
  push:
    branches:
      - try_deploy_ex_spec_to_GH_pages
  workflow_dispatch:

concurrency: ${{ github.ref }}

jobs:
 # release:
  #  uses: tomtom-internal/conan-reusable-workflows/.github/workflows/conan-release.yaml@095399d91ceddeb6799333f2dca5ec115ae08b97 # v2.10.2
   # secrets: inherit

  asciidoc:
    name: Deploy architecture documentation to GitHub Pages
   # needs: release
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
    if: needs.release.outputs.released-version != ''
    uses: ./.github/workflows/md-to-gh-pages.yaml
    with:
     # package_version: ${{ needs.release.outputs.released-version }}
      src_dir: .
      # Make sure this is outside of the src_dir
      build_dir: doc_build
