# Copyright (C) 2023 TomTom NV. All rights reserved.

---

name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.ref }}

jobs:
  release:
    uses: ./.github/workflows/custom_release.yml.yaml
    secrets: inherit

  deploy-ux-spec:
    name: Deploy UX spec to GitHub Pages and SharePoint
    needs: release
    if: needs.release.outputs.released-version != ''
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/deploy-ux-spec.yaml
    with:
      src_dir: .
      build_dir: nie-ux-spec
