# Copyright (C) 2023 TomTom NV. All rights reserved.
---

name: Release

on:
  push:
    branches:
      - try_deploy_ex_spec_to_GH_pages
  workflow_dispatch:

concurrency: ${{ github.ref }}

jobs:

  asciidoc:
    name: Deploy architecture documentation to GitHub Pages
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/convert-md-to-pdf.yaml
    with:
      #package_version: '1.1.0'
      src_dir: .
      # Make sure this is outside of the src_dir
      build_dir: doc_build
