# Copyright (C) 2023 TomTom NV. All rights reserved.

---

name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.ref }}

jobs:

  deploy-ux-spec:
    name: Deploy UX spec to GitHub Pages and SharePoint
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/deploy-ux-spec.yaml
    with:
      src_dir: .
      build_dir: doc_build
