name: 'Sharepoint Sync'

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Cloning repo
        uses: actions/checkout@v2

      - name: Publish to Sharepoint
        uses: obrassard/action-sharepoint-publish@v1.1.1
        with:
          site_url: 'https://tomtominternational.sharepoint.com/sites/nav-dx-guidance'
          library_folder: 'Shared Documents/nie-ux-spec'
          sharepoint_client_id: ${{ secrets.CLIENT_ID }}
          sharepoint_client_secret: ${{ secrets.CLIENT_SECRET }}