name: Download from SharePoint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Get Access Token
        id: get_token
        run: |
          echo "Requesting access token..."
          curl -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials" \
            -d "client_id=${{ secrets.CLIENT_ID }}" \
            -d "client_secret=${{ secrets.CLIENT_SECRET }}" \
            -d "scope=https://graph.microsoft.com/.default" \
            https://login.microsoftonline.com/${{ secrets.TENANT_ID }}/oauth2/v2.0/token \
            | jq -r '.access_token' > access_token.txt
          echo "Access token retrieved successfully."
          echo "${{ secrets.SP_ACCESS_TOKEN }}" > access_token.txt
          echo $(cat access_token.txt)


      - name: Get file content from SharePoint
        run: |
            
            DOWNLOAD_URL="https://graph.microsoft.com/v1.0/sites/055adf94-42e1-4941-8cd8-eb7ab60ca37d/drive/items/01HTWZYNWLWIF75TXITRAKXS72RFJ4NTTO/content"
            echo "Download URL: $DOWNLOAD_URL"
            
            response=$(curl -L -v -X GET \
              -H "Authorization: Bearer $(cat access_token.txt)" \
              -H "Accept: application/octet-stream" \
              -w "%{http_code}" \
              -o response.txt \
              "$DOWNLOAD_URL")
            
            if [ "$response" -eq 200 ]; then
              echo "File content retrieved successfully."
              echo "Response content:"
              cat response.txt
            else
              echo "Failed to retrieve file content. HTTP status code: $response"
              exit 1
            fi