name: Upload to SharePoint

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Upload file to SharePoint
        env:
          SP_ACCESS_TOKEN: ${{ secrets.SP_ACCESS_TOKEN }}  # Koristi access token iz tajni
          SP_SITE_URL: 'https://tomtominternational.sharepoint.com/sites/nav-dx-guidance'
          SP_FOLDER_PATH: 'Shared Documents/nie-ux-spec'  # Razmak nije enkodovan
        run: |
          # Definiši putanju do fajla
          FILE_PATH="README.md"
          FILE_NAME=$(basename "$FILE_PATH")

          # Provera da li fajl postoji
          if [ ! -f "$FILE_PATH" ]; then
            echo "Error: File $FILE_PATH not found!"
            exit 1
          fi

          # Formiranje URL-a za upload
          UPLOAD_URL="https://tomtominternational.sharepoint.com/sites/nav-dx-guidance/_api/web/getfolderbyserverrelativeurl('Shared%20Documents/nie-ux-spec')/files/add(overwrite=true, url='README.md')"
          echo "Upload URL: $UPLOAD_URL"  # Prikazivanje URL-a za debug

          # Otpremanje fajla
          curl -X POST -H "Authorization: Bearer $SP_ACCESS_TOKEN" \
            -H "Accept: application/json;odata=verbose" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$FILE_PATH" \
            "$UPLOAD_URL"
