name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Create a test file
        run: echo "test" > test.txt

      - name: SharePoint uploader
        uses: su-dont/share-point-uploader@v2.1
        with:
          sp_url: https://tomtominternational.sharepoint.com/sites/nav-dx-guidance
          sp_username: jana.milovanovic@tomtom.com
          sp_password: ${{ secrets.PASSWORD }}
          sp_folder: /Shared Documents/nie-ux-spec
          sp_file_name: share_point_text.txt
          file: test.txt