# Copyright (C) 2022 TomTom NV. All rights reserved.

---

name: Deploy UX spec to GitHub Pages and SharePoint
# GitHub Pages will be available at: https://fluffy-train-v716q7o.pages.github.io/
# Drive link: https://tomtominternational.sharepoint.com/sites/nav-dx-guidance/Shared%20Documents/nie-ux-spec/


on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy-ux-spec:
    name: Deploy UX spec to GitHub Pages and SharePoint
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: zip -r nie-ux-spec.zip 411173411___.md

      - name: Generate Access Token
        id: get_token
        run: |
          tenant_id="${{ secrets.TENANT_ID }}"
          client_id="${{ secrets.CLIENT_ID }}"
          client_secret="${{ secrets.CLIENT_SECRET }}"
          resource="https://graph.microsoft.com/.default"

          response=$(curl -X POST "https://login.microsoftonline.com/$tenant_id/oauth2/v2.0/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=$client_id" \
            -d "scope=$resource" \
            -d "client_secret=$client_secret" \
            -d "grant_type=client_credentials")

          access_token=$(echo $response | jq -r .access_token)
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV
          

      - name: Get merge commit date and hash
        id: get_commit_info
        run: |
          commit_hash="${GITHUB_SHA}"
          commit_date=$(git show -s --format=%cd --date=format:'%Y_%m_%d-%H:%M:%S' "$commit_hash")
          echo "COMMIT_DATE=$commit_date" >> $GITHUB_ENV
          echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV

      - name: Create upload session
        id: create_upload_session
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
          DRIVE_ID: ${{ secrets.DRIVE_ID }}
          FILE_NAME: 'nie-ux-spec-${{ env.COMMIT_DATE }}-${{ env.COMMIT_HASH }}.zip'
          FOLDER_NAME: 'nie-ux-spec'
        run: |
          upload_session=$(curl -X POST \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                  "item": {
                    "@microsoft.graph.conflictBehavior": "replace",
                    "name": "'"$FILE_NAME"'"
                  }
                }' \
            "https://graph.microsoft.com/v1.0/drives/$DRIVE_ID/root:/$FOLDER_NAME/$FILE_NAME:/createUploadSession")
          
          echo "UPLOAD_URL=$(echo $upload_session | jq -r .uploadUrl)" >> $GITHUB_ENV

      - name: Upload file in chunks
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          UPLOAD_URL: ${{ env.UPLOAD_URL }}
        run: |
          chunk_size=20971520  # 20 MB
          total_size=$(stat -c%s "nie-ux-spec.zip")
          offset=0
          
          while [ $offset -lt $total_size ]; do
              end=$((offset + chunk_size - 1))
              if [ $end -ge $total_size ]; then
                  end=$((total_size - 1))
              fi
          
              content_range="bytes $offset-$end/$total_size"
          
              dd if=nie-ux-spec.zip bs=1 skip=$offset count=$((end - offset + 1)) status=none | curl -X PUT \
                -H "Authorization: Bearer $ACCESS_TOKEN" \
                -H "Content-Range: $content_range" \
                --data-binary @- \
                "$UPLOAD_URL"
          
              offset=$((offset + chunk_size))
          done
