name: 'Sharepoint Sync'

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Cloning repo # This step is required
        uses: actions/checkout@v2

      - name: Publish to Sharepoint
        uses: obrassard/action-sharepoint-publish@v1.0.1
        with:
          site_url: 'https://you.sharepoint.com/sites/mySite'
          library_folder: 'Shared documents/releases'
          sharepoint_user: ${{ secrets.CLIENT_ID }}
          sharepoint_password: ${{ secrets.CLIENT_SECRET }}