name: Upload ZIP to OneDrive

on:
  workflow_dispatch:


jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP archive
        run: zip -r archive.zip .  # Kreira ZIP arhivu svih datoteka u trenutnom direktorijumu

      - name: Get Access Token
        id: get_token
        run: |
          response=$(curl -X POST "https://login.microsoftonline.com/${{ secrets.TENANT_ID }}/oauth2/v2.0/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "client_id=${{ secrets.CLIENT_ID }}" \
          -d "scope=https://graph.microsoft.com/.default" \
          -d "client_secret=${{ secrets.CLIENT_SECRET }}" \
          -d "grant_type=client_credentials")
          echo "::set-output name=token::$(echo $response | jq -r .access_token)"

      - name: Upload to OneDrive
        run: |
          curl -X PUT "https://graph.microsoft.com/v1.0/me/drive/root:/archive.zip/content" \
          -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
          -H "Content-Type: application/zip" \
          --data-binary @archive.zip
