// Copyright (C) 2020 TomTom NV. All rights reserved.
//
// This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
// used for internal evaluation purposes or commercial use strictly subject to separate
// license agreement between you and TomTom NV. If you are the licensee, you are only permitted
// to use this software in accordance with the terms of your license agreement. If you are
// not the licensee, you are not authorized to use this software in any manner and should
// immediately return or destroy it.

[[section-overall-architecture]]

== Overall Architecture

=== `LaneGuidanceProvider`
This class implements the interface towards TripOnboardService (TOBS) and orchestrates the work of other components to
deliver `LaneGuidanceScenario` back to TOBS.

Most of the logic (which is common between single threaded use and use by a worker thread) is extracted to
`LaneGuidanceProviderBase`. There is one abstract member function to be implemented in an inherited class -
`LaneGuidanceProviderBase::OnScenarioNeeded()`.

Once `LaneGuidanceProvider` gets scenario instructions via `SetScenarioInstructions` if a scenario is needed a call
`LaneGuidanceProviderBase::OnScenarioNeeded()` happens. This should trigger the calculation of a new scenario(or just
build a scenario immediately in the synchronous implementation).

Once scenario is ready `LaneGuidanceScenario` starts tracking it.

Scenario might be changed after `LaneGuidanceProvider::SetAnnouncementPhase()` or `LaneGuidanceProvider::SetPosition()`
calls. `SetPosition` updates current lane segment and may reset the scenario to empty if current position bigger than the
scenario end. `SetAnnouncementPhase` may update the current maneuver segment and the announcement phase.

Passing the end of the tracked scenario stops tracking it. Setting another instructions list leads to building a new
scenario and once it's ready stops tracking the current.

Every time the tracked scenario gets changed(including setting a new scenario and resetting)
`LaneGuidanceProvider` issues a callback `OnLaneGuidanceScenarioChanged`.
